### ISSUE TITLE
[BUG][l10n_br_sale] provavel regressao no l10n_br_sale/report/sale_report_templates.xml

### ISSUE THREAD

**Issue by rvalyi** [OCA/l10n-brazil#1199]
fazendo: `odoo -d br -i l10n_br_sale --stop-after-init`acontece esse erro:

```
2021-03-10 04:21:46,427 523 INFO br odoo.models: Storing computed values of sale.order.line.cofins_cst_code 
2021-03-10 04:21:46,428 523 INFO br odoo.models: Storing computed values of sale.order.line.cofinsst_cst_code 
2021-03-10 04:21:46,429 523 INFO br odoo.models: Storing computed values of sale.order.line.pis_cst_code 
2021-03-10 04:21:46,430 523 INFO br odoo.models: Storing computed values of sale.order.line.pisst_cst_code 
2021-03-10 04:21:47,073 523 INFO br odoo.modules.loading: loading l10n_br_sale/data/company.xml 
2021-03-10 04:21:47,086 523 INFO br odoo.modules.loading: loading l10n_br_sale/security/ir.model.access.csv 
2021-03-10 04:21:47,134 523 INFO br odoo.modules.loading: loading l10n_br_sale/security/l10n_br_sale_security.xml 
2021-03-10 04:21:47,456 523 INFO br odoo.modules.loading: loading l10n_br_sale/views/res_config_settings_view.xml 
2021-03-10 04:21:47,668 523 INFO br odoo.modules.loading: loading l10n_br_sale/views/res_company_view.xml 
2021-03-10 04:21:47,759 523 INFO br odoo.modules.loading: loading l10n_br_sale/views/sale_view.xml 
2021-03-10 04:21:48,012 523 INFO br odoo.modules.loading: loading l10n_br_sale/report/sale_report_view.xml 
2021-03-10 04:21:48,060 523 INFO br odoo.modules.loading: loading l10n_br_sale/report/sale_report_templates.xml 
2021-03-10 04:21:48,096 523 INFO br odoo.addons.base.models.ir_ui_view: Element '<xpath expr="//tbody[hasclass('sale_tbody')]//t[@t-as='line']/tr/t[@t-if='not line.display_type']/td[@name='td_taxes']">' cannot be located in parent view

Error context:
View `report_saleorder_document_l10n_br_sale`
[view_id: 902, xml_id: n/a, model: n/a, parent_id: 808] 
2021-03-10 04:21:48,103 523 WARNING br odoo.modules.loading: Transient module states were reset 
2021-03-10 04:21:48,111 523 ERROR br odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/odoo/src/odoo/models.py", line 1126, in _validate_fields
    check(self)
  File "/odoo/src/odoo/addons/base/models/ir_ui_view.py", line 345, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/odoo/src/odoo/addons/base/models/ir_ui_view.py", line 814, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/odoo/src/odoo/addons/base/models/ir_ui_view.py", line 762, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/odoo/src/odoo/addons/base/models/ir_ui_view.py", line 740, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "/odoo/src/odoo/addons/base/models/ir_ui_view.py", line 568, in raise_view_error
    raise ValueError(message)
ValueError: Element '<xpath expr="//tbody[hasclass('sale_tbody')]//t[@t-as='line']/tr/t[@t-if='not line.display_type']/td[@name='td_taxes']">' cannot be located in parent view

Error context:
View `report_saleorder_document_l10n_br_sale`
[view_id: 902, xml_id: n/a, model: n/a, parent_id: 808]

During handling of the above exception, another exception occurred:

```

O problema é esse xpath https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_sale/report/sale_report_templates.xml#L6 me parece especifico demais e nao é encontrado.

No Travis e Runbot a instalaçao funciona mas é provavel que tem algum modulo a mais instalado antes que faz que o xpath funciona e nao nesse teste simples.

cc @renatonlima @mbcosta

**Comment by marcos-mendez** [comment]
@rvalyi eu estive vendo em outras localizacoes e na ha a substituicao do campo, simplesmente e abordado um outro modelo completamente diferente. Sera que nao e isso? Nos adotamos a mesma arquitetura?

**Comment by mbcosta** [comment]
@rvalyi não consegui reproduzir o erro, o teste que fiz foi criar um novo Banco de Dados e rodar o mesmo comando que você fez odoo -d br -i l10n_br_sale --stop-after-init , por favor poderia confirmar esse BUG ? Pode existir um outro modulo que também esteja fazendo alterações no arquivo e isso está causando conflito talvez por causa do 'replace' mas a instalação direta do modulo não parece causar erro.

@marcos-mendez pelo que entendi a sua sugestão seria criar um novo arquivo, se for isso eu acredito que só seria justificado se as alterações necessárias para adaptar a localização fossem muitas, maior que 50% do arquivo original, já que também podem existir outros módulos da OCA que incluem campos no leiaute e tendo um outro arquivo para o Pedido de Venda essas alterações precisariam ser feitas na localização pois o leiaute do core não estaria sendo usado.

**Comment by marcos-mendez** [comment]
@mbcosta Maninho eu sugeri da minha ignorancia. Nao sei se eh a solução mas passei por esse problema tambem

**Comment by rvalyi** [comment]
consegui reproduzir instalando nessa ordem:
```
odoo -i l10n_br_fiscal --stop-after-init
odoo -i l10n_br_account --stop-after-init
odoo -i -i l10n_br_sale --stop-after-init
```

resolvido por https://github.com/OCA/l10n-brazil/pull/1391
