### ISSUE TITLE
[BUG] Faturamento

### ISSUE THREAD

**Issue by marcos-mendez** [OCA/l10n-brazil#1229]
** Descreva o bug **
Ao acessar com debug=true nas configuracoes de faturamento (FATURAMENT>CONFIGURACOES>MODOS DE PAGAMENTO) eh gerado um erro que nao permite criacao de modos de pagamento

Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 755, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 728, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1394, in load_views
    for [v_id, v_type] in views
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1394, in <dictcomp>
    for [v_id, v_type] in views
  File "/usr/lib/python3/dist-packages/odoo/custom-addons/geospatial/base_geoengine/geo_model.py", line 107, in fields_view_get
    submenu=submenu)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1480, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1131, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 568, in raise_view_error
    raise ValueError(message)
ValueError: O campo `operation_type` não existe

Contexto de erro:
Veja `n/a`
[view_id: n/a, xml_id: n/a, model: n/a, parent_id: n/a]

**Comment by renatonlima** [comment]
@marcos-mendez,

Qual branch da OCA/l10n-brazil você esta utilizando? e quais módulos da localização você tem instalado no seu ambiente?

**Comment by rvalyi** [comment]
(@marcos-mendez 1 ano atras, o campo do tipo da operaçao se chamava operation_type no l10n_br_brazil. Porem a gente teve que mudar para fiscal_operation_type e fiscal_operation_id porque senao a gente pevaga conflitos com o modulo de mrp que tb usa esses nomes. Isso foi feito no PR https://github.com/OCA/l10n-brazil/pull/855 com o devido script de migraçao. Seu problema parece um pouco ligado a isso, como se vc nao tivesse migrado o seu banco o misturando codigo recente e antigo).

**Comment by marcos-mendez** [comment]
Oi Rafael, parece que foi algum rebase que passou sujo e ninguem viu, segundo o que o @marcelsavegnago me explicou. Vou fechar pois depois de testar no runbot deu certo.
