### ISSUE TITLE
[BUG]Erro instalação l10n_br_sale

### ISSUE THREAD

**Issue by vanderleiromera** [OCA/l10n-brazil#1257]
** Descreva o bug **
Ao tentar instalar o modulo l10n_br_sale no db novo apresentado o seguinte erro:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/vanderlei/Projects/odoo12/core/odoo/models.py", line 1128, in _validate_fields
    check(self)
  File "/home/vanderlei/Projects/odoo12/core/odoo/addons/base/models/ir_ui_view.py", line 345, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/home/vanderlei/Projects/odoo12/core/odoo/addons/base/models/ir_ui_view.py", line 821, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/home/vanderlei/Projects/odoo12/core/odoo/addons/base/models/ir_ui_view.py", line 769, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/home/vanderlei/Projects/odoo12/core/odoo/addons/base/models/ir_ui_view.py", line 747, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "/home/vanderlei/Projects/odoo12/core/odoo/addons/base/models/ir_ui_view.py", line 568, in raise_view_error
    raise ValueError(message)
ValueError: Element '<xpath expr="//field[@name='discount']">' cannot be located in parent view

Error context:
View `account.invoice.line.form`
[view_id: 1302, xml_id: n/a, model: account.invoice.line, parent_id: 547]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vanderlei/Projects/odoo12/core/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/vanderlei/Projects/odoo12/core/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/home/vanderlei/Projects/odoo12/core/odoo/models.py", line 3908, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/vanderlei/Projects/odoo12/core/odoo/models.py", line 3822, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/home/vanderlei/Projects/odoo12/core/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/home/vanderlei/Projects/odoo12/core/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/home/vanderlei/Projects/odoo12/core/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/home/vanderlei/Projects/odoo12/core/odoo/models.py", line 3639, in create
    fields[0].determine_inverse(batch_recs)
  File "/home/vanderlei/Projects/odoo12/core/odoo/fields.py", line 1201, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/vanderlei/Projects/odoo12/core/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/home/vanderlei/Projects/odoo12/core/odoo/addons/base/models/ir_ui_view.py", line 445, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/home/vanderlei/Projects/odoo12/core/odoo/models.py", line 3364, in write
    self._write(store_vals)
  File "/home/vanderlei/Projects/odoo12/core/odoo/models.py", line 3500, in _write
    self._validate_fields(vals)
  File "/home/vanderlei/Projects/odoo12/core/odoo/models.py", line 1132, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nElement \'<xpath expr="//field[@name=\'discount\']">\' cannot be located in parent view\n\nError context:\nView `account.invoice.line.form`\n[view_id: 1302, xml_id: n/a, model: account.invoice.line, parent_id: 547]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vanderlei/Projects/odoo12/core/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/vanderlei/Projects/odoo12/core/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/vanderlei/Projects/odoo12/core/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/vanderlei/Projects/odoo12/core/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/home/vanderlei/Projects/odoo12/core/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/vanderlei/Projects/odoo12/core/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/vanderlei/Projects/odoo12/core/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/vanderlei/Projects/odoo12/core/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/vanderlei/Projects/odoo12/core/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/vanderlei/Projects/odoo12/core/addons/web/controllers/main.py", line 967, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/vanderlei/Projects/odoo12/core/addons/web/controllers/main.py", line 955, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/vanderlei/Projects/odoo12/core/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/vanderlei/Projects/odoo12/core/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/home/vanderlei/Projects/odoo12/core/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/vanderlei/Projects/odoo12/core/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/vanderlei/Projects/odoo12/core/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/vanderlei/Projects/odoo12/core/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/vanderlei/Projects/odoo12/core/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/vanderlei/Projects/odoo12/core/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/vanderlei/Projects/odoo12/core/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/home/vanderlei/Projects/odoo12/core/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/vanderlei/Projects/odoo12/core/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/vanderlei/Projects/odoo12/core/odoo/tools/convert.py", line 865, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/vanderlei/Projects/odoo12/core/odoo/tools/convert.py", line 764, in parse
    exc_info[2]
  File "/home/vanderlei/Projects/odoo12/core/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/vanderlei/Projects/odoo12/core/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/vanderlei/Projects/odoo12/core/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/home/vanderlei/Projects/odoo12/core/odoo/models.py", line 3908, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/vanderlei/Projects/odoo12/core/odoo/models.py", line 3822, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/home/vanderlei/Projects/odoo12/core/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/home/vanderlei/Projects/odoo12/core/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/home/vanderlei/Projects/odoo12/core/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/home/vanderlei/Projects/odoo12/core/odoo/models.py", line 3639, in create
    fields[0].determine_inverse(batch_recs)
  File "/home/vanderlei/Projects/odoo12/core/odoo/fields.py", line 1201, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/vanderlei/Projects/odoo12/core/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/home/vanderlei/Projects/odoo12/core/odoo/addons/base/models/ir_ui_view.py", line 445, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/home/vanderlei/Projects/odoo12/core/odoo/models.py", line 3364, in write
    self._write(store_vals)
  File "/home/vanderlei/Projects/odoo12/core/odoo/models.py", line 3500, in _write
    self._validate_fields(vals)
  File "/home/vanderlei/Projects/odoo12/core/odoo/models.py", line 1132, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Element '<xpath expr="//field[@name='discount']">' cannot be located in parent view

Error context:
View `account.invoice.line.form`
[view_id: 1302, xml_id: n/a, model: account.invoice.line, parent_id: 547]
None" while parsing /home/vanderlei/Projects/odoo12/core/addons/sale/views/sale_views.xml:1083, near
<record model="ir.ui.view" id="account_invoice_line_form">
            <field name="name">account.invoice.line.form</field>
            <field name="model">account.invoice.line</field>
            <field name="inherit_id" ref="account.view_invoice_line_form"/>
            <field name="arch" type="xml">
                <data>
                    <xpath expr="//field[@name='discount']" position="attributes">
                        <attribute name="groups">sale.group_discount_per_so_line</attribute>
                    </xpath>
                </data>
            </field>
        </record>

**Comment by marcos-mendez** [comment]
Isso foi resolvido no ultimo merge, você tem que atualizar a localização.

Cuidado pois a 12 da main-branch ainda não está 100% estável. Talvez tenha que desinstalar a l10n_brazil fazer um git pull, reiniciarias o serviço odoo e re-instalar a l10n_brazil

Ai pra fazer tudo de uma vez aumenta o CPU max execution e o Memorry Max pra fazer a instalação a l10n_br

Foi assim que eu resolvi no meu caso

**Comment by vanderleiromera** [comment]
Valeu @marcos-mendez vou proceder dessa maneira, obrigado!

Resolvido com #1263
