### ISSUE TITLE
[BUG]12.0 NCM - Erro ao Digitar no campo

### ISSUE THREAD

**Issue by vanderleiromera** [OCA/l10n-brazil#1472]
Editar o produto 
Aba - fiscal
Campo - Ncm

Ao digitar no campo NCM, para filtrar os ncms, apresenta esse erro..

Error:
Uncaught TypeError: Cannot read property 'split' of undefined

http://3487937-12-0-ab5ef0.runbot2-3.odoo-community.org/web/content/678-1986502/web.assets_backend.js:1216
Traceback:
TypeError: Cannot read property 'split' of undefined
    at Class._getDisplayName (http://3487937-12-0-ab5ef0.runbot2-3.odoo-community.org/web/content/678-1986502/web.assets_backend.js:1216:101)
    at http://3487937-12-0-ab5ef0.runbot2-3.odoo-community.org/web/content/678-1986502/web.assets_backend.js:1221:219
    at Function._.map._.collect (http://3487937-12-0-ab5ef0.runbot2-3.odoo-community.org/web/content/677-3c963e7/web.assets_common.js:13:270)
    at Object.<anonymous> (http://3487937-12-0-ab5ef0.runbot2-3.odoo-community.org/web/content/678-1986502/web.assets_backend.js:1221:186)
    at Object.<anonymous> (http://3487937-12-0-ab5ef0.runbot2-3.odoo-community.org/web/content/677-3c963e7/web.assets_common.js:802:681)
    at fire (http://3487937-12-0-ab5ef0.runbot2-3.odoo-community.org/web/content/677-3c963e7/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://3487937-12-0-ab5ef0.runbot2-3.odoo-community.org/web/content/677-3c963e7/web.assets_common.js:801:198)
    at Object.deferred.<computed> [as resolve] (http://3487937-12-0-ab5ef0.runbot2-3.odoo-community.org/web/content/677-3c963e7/web.assets_common.js:803:56)
    at Object.<anonymous> (http://3487937-12-0-ab5ef0.runbot2-3.odoo-community.org/web/content/677-3c963e7/web.assets_common.js:3589:448)
    at Object.<anonymous> (http://3487937-12-0-ab5ef0.runbot2-3.odoo-community.org/web/content/677-3c963e7/web.assets_common.js:802:681)

**Comment by marcelsavegnago** [comment]
@vanderleiromera esse aqui vc chegou testar no runbot tbm ? Se não me engano @rvalyi ou o @renatonlima haviam feito uma correção relacionada com este assunto.

**Comment by vanderleiromera** [comment]
Opa, testei sim, inclusive o log é do runbot

**Comment by vanderleiromera** [comment]
Corrigido com #1477
