### ISSUE TITLE
[BUG]12.0 - Alterar Default document type

### ISSUE THREAD

**Issue by vanderleiromera** [OCA/l10n-brazil#1473]
![image](https://user-images.githubusercontent.com/65144026/121963912-5e59cd80-cd30-11eb-8ea4-535f05c706df.png)
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-12.0/addons/web/controllers/main.py", line 963, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/odoo-12.0/addons/web/controllers/main.py", line 955, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 755, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 728, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/models.py", line 1396, in load_views
    for [v_id, v_type] in views
  File "/.repo_requirements/odoo/odoo/models.py", line 1396, in <dictcomp>
    for [v_id, v_type] in views
  File "/home/odoo/build/OCA/l10n-brazil/l10n_br_fiscal/models/data_abstract.py", line 46, in fields_view_get
    orm.setup_modifiers(node)
UnboundLocalError: local variable 'node' referenced before assignment

**Comment by marcelsavegnago** [comment]
@vanderleiromera fez o teste no runbot ?

**Comment by vanderleiromera** [comment]
Isso, apresentou erro no local, fui no rubont e deu o mesmo erro.

**Comment by rpsjr** [comment]
Este mesmo erro ocorre ao acionar "App Fiscal -> Configuration - > Fiscal Document".

Environment: http://3488390-12-0-13c76a.runbot1-3.odoo-community.org/web?debug=#action=526&model=l10n_br_fiscal.certificate&view_type=list&menu_id=348

![image](https://user-images.githubusercontent.com/42212369/122952845-a55d4980-d354-11eb-98c5-64bedd99ffe8.png)
