### ISSUE TITLE
12.0[BUG] - Lentidão e erro ao acessar o account.invoice

### ISSUE THREAD

**Issue by vanderleiromera** [OCA/l10n-brazil#1609]
Hoje me deparei com isso, as vezes abre a fatura, e outras obtenho erro. 

`2021-09-01 17:19:27,291 40500 INFO eipprod odoo.addons.base.models.ir_cron: Starting job `Post process payment transactions`. 
2021-09-01 17:19:27,655 40500 INFO eipprod odoo.addons.base.models.ir_cron: Job `Post process payment transactions` done. 
2021-09-01 17:19:33,675 40483 ERROR eipprod odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/home/vanderlei/Projects/odooprod/core/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 825

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vanderlei/Projects/odooprod/core/odoo/fields.py", line 1064, in __get__
    value = record.env.cache.get(record, self)
  File "/home/vanderlei/Projects/odooprod/core/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('account.invoice(825,).amount_discount_value', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vanderlei/Projects/odooprod/core/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 719

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vanderlei/Projects/odooprod/core/odoo/fields.py", line 1064, in __get__
    value = record.env.cache.get(record, self)
  File "/home/vanderlei/Projects/odooprod/core/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('l10n_br_fiscal.document(719,).amount_discount_value', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vanderlei/Projects/odooprod/core/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 14038

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vanderlei/Projects/odooprod/core/odoo/fields.py", line 1064, in __get__
    value = record.env.cache.get(record, self)
  File "/home/vanderlei/Projects/odooprod/core/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('l10n_br_fiscal.document.line(14038,).amount_untaxed', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vanderlei/Projects/odooprod/core/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 14038

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vanderlei/Projects/odooprod/core/odoo/fields.py", line 1064, in __get__
    value = record.env.cache.get(record, self)
  File "/home/vanderlei/Projects/odooprod/core/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('l10n_br_fiscal.document.line(14038,).currency_id', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vanderlei/Projects/odooprod/core/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 14038

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vanderlei/Projects/odooprod/core/odoo/fields.py", line 1064, in __get__
    value = record.env.cache.get(record, self)
  File "/home/vanderlei/Projects/odooprod/core/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('l10n_br_fiscal.document.line(14038,).company_id', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vanderlei/Projects/odooprod/core/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/vanderlei/Projects/odooprod/core/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/vanderlei/Projects/odooprod/core/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/vanderlei/Projects/odooprod/core/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/home/vanderlei/Projects/odooprod/core/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/vanderlei/Projects/odooprod/core/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/vanderlei/Projects/odooprod/core/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/vanderlei/Projects/odooprod/core/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/vanderlei/Projects/odooprod/core/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/vanderlei/Projects/odooprod/core/addons/web/controllers/main.py", line 963, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/vanderlei/Projects/odooprod/core/addons/web/controllers/main.py", line 955, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/vanderlei/Projects/odooprod/core/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/vanderlei/Projects/odooprod/core/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/vanderlei/Projects/odooprod/core/odoo/models.py", line 2837, in read
    vals[name] = convert(record[name], record, use_name_get)
  File "/home/vanderlei/Projects/odooprod/core/odoo/models.py", line 5169, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/vanderlei/Projects/odooprod/core/odoo/fields.py", line 1068, in __get__
    self.determine_value(record)
  File "/home/vanderlei/Projects/odooprod/core/odoo/fields.py", line 1181, in determine_value
    self.compute_value(recs)
  File "/home/vanderlei/Projects/odooprod/core/odoo/fields.py", line 1135, in compute_value
    self._compute_value(records)
  File "/home/vanderlei/Projects/odooprod/core/odoo/fields.py", line 1128, in _compute_value
    self.compute(records)
  File "/home/vanderlei/Projects/odooprod/core/odoo/fields.py", line 649, in _compute_related
    record[self.name] = value[self.related_field.name]
  File "/home/vanderlei/Projects/odooprod/core/odoo/models.py", line 5169, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/vanderlei/Projects/odooprod/core/odoo/fields.py", line 1068, in __get__
    self.determine_value(record)
  File "/home/vanderlei/Projects/odooprod/core/odoo/fields.py", line 1181, in determine_value
    self.compute_value(recs)
  File "/home/vanderlei/Projects/odooprod/core/odoo/fields.py", line 1135, in compute_value
    self._compute_value(records)
  File "/home/vanderlei/Projects/odooprod/core/odoo/fields.py", line 1126, in _compute_value
    getattr(records, self.compute)()
  File "/home/vanderlei/Projects/odooprod/l10n-brazil/l10n_br_fiscal/models/document_fiscal_mixin_methods.py", line 45, in _compute_amount
    values[field] += line[field]
  File "/home/vanderlei/Projects/odooprod/core/odoo/models.py", line 5169, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/vanderlei/Projects/odooprod/core/odoo/fields.py", line 1068, in __get__
    self.determine_value(record)
  File "/home/vanderlei/Projects/odooprod/core/odoo/fields.py", line 1181, in determine_value
    self.compute_value(recs)
  File "/home/vanderlei/Projects/odooprod/core/odoo/fields.py", line 1135, in compute_value
    self._compute_value(records)
  File "/home/vanderlei/Projects/odooprod/core/odoo/fields.py", line 1126, in _compute_value
    getattr(records, self.compute)()
  File "/home/vanderlei/Projects/odooprod/l10n-brazil/l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py", line 120, in _compute_amounts
    round_curr = record.currency_id.round
  File "/home/vanderlei/Projects/odooprod/core/odoo/fields.py", line 1068, in __get__
    self.determine_value(record)
  File "/home/vanderlei/Projects/odooprod/core/odoo/fields.py", line 1181, in determine_value
    self.compute_value(recs)
  File "/home/vanderlei/Projects/odooprod/core/odoo/fields.py", line 1135, in compute_value
    self._compute_value(records)
  File "/home/vanderlei/Projects/odooprod/core/odoo/fields.py", line 1128, in _compute_value
    self.compute(records)
  File "/home/vanderlei/Projects/odooprod/core/odoo/fields.py", line 646, in _compute_related
    values = [first(value[name]) for value in values]
  File "/home/vanderlei/Projects/odooprod/core/odoo/fields.py", line 646, in <listcomp>
    values = [first(value[name]) for value in values]
  File "/home/vanderlei/Projects/odooprod/core/odoo/models.py", line 5169, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/vanderlei/Projects/odooprod/core/odoo/fields.py", line 1068, in __get__
    self.determine_value(record)
  File "/home/vanderlei/Projects/odooprod/core/odoo/fields.py", line 1171, in determine_value
    record._prefetch_field(self)
  File "/home/vanderlei/Projects/odooprod/core/odoo/models.py", line 2882, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/home/vanderlei/Projects/odooprod/core/odoo/models.py", line 2820, in read
    self._read_from_database(stored, inherited)
  File "/home/vanderlei/Projects/odooprod/core/odoo/models.py", line 2974, in _read_from_database
    self.env.cache.update(fetched, field, values)
  File "/home/vanderlei/Projects/odooprod/core/odoo/api.py", line 1063, in update
    self._data[key][field].update(pycompat.izip(records._ids, values))
MemoryError
2021-09-01 17:19:33,688 40483 INFO eipprod werkzeug: 127.0.0.1 - - [01/Sep/2021 17:19:33] "POST /web/dataset/call_kw/account.invoice/read HTTP/1.0" 200 - 195 1.178 30.756
2021-09-01 17:19:33,689 40483 INFO eipprod odoo.service.server: Worker (40483) virtual memory limit (713109504) reached. `

**Comment by mbcosta** [comment]
@vanderleiromera quais parâmetros você está usando para iniciar o serviço do Odoo? Veja se o parâmetro workers está sendo definido, exemplo:
$ odoo --workers 0

https://www.odoo.com/documentation/12.0/developer/reference/cmdline.html

**Comment by rvalyi** [comment]
@vanderleiromera ainda nao esta claro o que ta acontescendo. Uma forma de ver é de vc botar alguns prints estrategicos em metotods dessa stack, para ver de que registros e campos se trata, depois olhar o SQL deles para ver se tem alguma anomalia. Agora, te digo que para quase todos projetos em prod, a gente costuma aumentar a memoria limite dos workers porque é facil o limite padrão não dar conta. Mesma coisa com o Postgres, os parâmetros padrão não são legais para prod.

Examplos de limites que a gente usa num projeto no arquivo de configuraçao /etc/odoo.cfg:

```
limit_memory_soft = 5147483648
limit_memory_hard = 5684354560
limit_request = 8192
limit_time_cpu = 6000000
limit_time_real = 12000000
limit_time_real_cron = 600
```

**Comment by vanderleiromera** [comment]
@rvalyi obrigado pelo retorno, vou checar os limites do conf pra ver o comportamento.

**Comment by vanderleiromera** [comment]
> @vanderleiromera quais parâmetros você está usando para iniciar o serviço do Odoo? Veja se o parâmetro workers está sendo definido, exemplo:
> $ odoo --workers 0
> 
> https://www.odoo.com/documentation/12.0/developer/reference/cmdline.html

@mbcosta obrigado pelo retorno, estou usando workers = 5, pois com 0 estava dando erro com longpolling usando nginx, mas estava tudo bem, hoje que veio apresentar essa lentidão.

**Comment by vanderleiromera** [comment]
Alterado os parâmetros limit do conf não recebo mais o erro, porem ainda continuo com lentidão ao abrir a fatura, topando a cpu por alguns segundos.. mas parece persistir um problema localizado, sigo analizando...

**Comment by rvalyi** [comment]
Podem ter muitos motivos, pode ser algum módulo, alguma customização. Primeira coisa, vê com top se a demora vem de um processo Odoo/Python ou se vem do Potsgres. Vc pode tb usar pg_activity para ver as queries lentas. Botar uns prints... Pode precisar adicionar um Index, talvez optimizar uma query...
Vê a questão dos N+1 queries nos loops...

Para saber, é uma fatura com muitas linhas? As vezes faturas com 50 linhas ou mais podem ser lentas com alguns módulos...

**Comment by vanderleiromera** [comment]
Oh @rvalyi obrigado pelo feedback, qualquer fatura topa a cpu, assim que abrir ela, mesmo com uma linha, não tenho customização..

![load_invoice](https://user-images.githubusercontent.com/65144026/131902672-bf3ec769-317a-491d-b4b3-dedfe35e43b2.png)
![loadcpu](https://user-images.githubusercontent.com/65144026/131902687-1bc69874-1935-41ce-84a2-d7c1c029ac4f.png)


vou seguir suas orientações pra identificar o problema. Grato

**Comment by marcelsavegnago** [comment]
> Alterado os parâmetros limit do conf não recebo mais o erro, porem ainda continuo com lentidão ao abrir a fatura, topando a cpu por alguns segundos.. mas parece persistir um problema localizado, sigo analizando...

por desencargo faz um select na tabela de linhas do documento fiscal. Eu tive uma situação (nao chequei se está ocorrendo novamente) de ter diversas linhas na tabela de linhas dos documentos fiscais que nao faziam sentido estar lah :D... masss isso estava afetando bastante a performance.

**Comment by vanderleiromera** [comment]
Show @marcelsavegnago  vou dar uma olhada nisso, valeu!
