### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by marcos-mendez** [OCA/l10n-brazil#1693]
** Descreva o bug **
Ao tentar instalar o l10n_br_fiscal obtenho o seguinte erro

`Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-72>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 474, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 592, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 455, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 780, in convert_xml_import
    relaxng = etree.RelaxNG(etree.parse(schema))
  File "src/lxml/etree.pyx", line 3435, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1840, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1866, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1770, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1163, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 651, in lxml.etree._raiseParseError
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
  File "b'/usr/lib/python3/dist-packages/odoo/import_xml.rng'", line 0
lxml.etree.XMLSyntaxError: <no detail available>`

** Capturas de tela **
![Screenshot from 2021-11-01 12-19-21](https://user-images.githubusercontent.com/38361760/139695671-e84d0b1e-6fc2-4eff-a4b8-a317d860026b.png)

**Comment by rvalyi** [comment]
tenta passar os logs antes da exceção para ver se a gente consegue ver o ultimo XML que da problema.

**Comment by marcos-mendez** [comment]
@rvalyi só aparece isso aqui.

`2021-11-01 15:43:10,187 33835 INFO kimenz-prod odoo.modules.loading: loading 90 modules... 
2021-11-01 15:43:10,188 33835 INFO kimenz-prod odoo.modules.loading: Loading module l10n_br_fiscal (46/90) 
2021-11-01 15:43:11,445 33835 INFO kimenz-prod odoo.modules.registry: module l10n_br_fiscal: creating or updating database tables 
2021-11-01 15:43:11,560 33841 INFO ? werkzeug: 192.168.1.160 - - [01/Nov/2021 15:43:11] "GET /web/static/src/img/spin.png HTTP/1.1" 304 - - - -
2021-11-01 15:43:14,449 33835 WARNING kimenz-prod odoo.addons.base.models.ir_model: Two fields (district, district_id) of fsm.location() have the same label: District. 
2021-11-01 15:43:15,176 33835 INFO kimenz-prod odoo.models: Storing computed values of res.company.simplifed_tax_id 
2021-11-01 15:43:15,177 33835 INFO kimenz-prod odoo.models: Storing computed values of res.company.simplifed_tax_range_id 
2021-11-01 15:43:15,177 33835 INFO kimenz-prod odoo.models: Storing computed values of res.company.simplifed_tax_percent 
2021-11-01 15:43:15,177 33835 INFO kimenz-prod odoo.models: Storing computed values of res.company.coefficient_r 
2021-11-01 15:43:15,177 33835 INFO kimenz-prod odoo.models: Storing computed values of res.company.coefficient_r_percent 
2021-11-01 15:43:18,536 33835 INFO kimenz-prod odoo.modules.loading: loading l10n_br_fiscal/security/fiscal_security.xml 
2021-11-01 15:43:18,561 33845 INFO kimenz-prod longpolling: 192.168.1.160 - - [2021-11-01 15:43:18] "POST /longpolling/im_status HTTP/1.0" 200 509 5.082014 
2021-11-01 15:43:18,580 33835 WARNING kimenz-prod odoo.modules.loading: Transient module states were reset 
2021-11-01 15:43:18,585 33835 ERROR kimenz-prod odoo.modules.registry: Failed to load registry 
2021-11-01 15:43:18,585 33835 ERROR kimenz-prod odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-72>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 474, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 592, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 455, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 780, in convert_xml_import
    relaxng = etree.RelaxNG(etree.parse(schema))
  File "src/lxml/etree.pyx", line 3435, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1840, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1866, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1770, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1163, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 651, in lxml.etree._raiseParseError
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
  File "b'/usr/lib/python3/dist-packages/odoo/import_xml.rng'", line 0
lxml.etree.XMLSyntaxError: <no detail available>
`

Será que tem algo aver com o pyopenssl que instala na v21 e o erp.brasil pede a versao 19?

**Comment by marcos-mendez** [comment]
@rvalyi fiz as mesmas configurações do travis e efetivamente o erro continua. Acredito que seja algum problema de versão do xmlsec, Vou remove-lo e instalar a versão downgraded pra ver se rola.

**Comment by marcos-mendez** [comment]
Não funcionou com o xmlsec 19

**Comment by rvalyi** [comment]
Não acho que tem a ver com xmlsec. Vc pode verificar que vc tem exactamente a branch 14.0 da OCA com nenhum diff local (com git status no seu clone por exemplo)?

Ou tenta fazer um clone do repo de novo.

**Comment by marcos-mendez** [comment]
Cara 0 Diff @rafa

Em seg., 1 de nov. de 2021 às 14:17, Raphaël Valyi ***@***.***>
escreveu:

**Comment by rvalyi** [comment]
A dependência a lib xmlsec foi removida na lib erpbrasil.assinatura. portanto eu acho que foi solucionado.
