### ISSUE TITLE
[BUG][14.0] Erro ao tentar instalar o l10n_br_fiscal

### ISSUE THREAD

**Issue by llRedXD** [OCA/l10n-brazil#1710]
Erro de instalação do modulo 

![imagem_2021-11-18_103451](https://user-images.githubusercontent.com/59977779/142425015-bbda1642-747e-470c-afc5-8eee6cd79568.png)

``` Traceback (most recent call last):
  File "/home/gabriel/oca/odoo/core/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/gabriel/oca/odoo/core/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/home/gabriel/oca/odoo/core/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/gabriel/oca/odoo/core/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/gabriel/oca/odoo/core/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/gabriel/oca/odoo/core/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/home/gabriel/oca/odoo/core/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/home/gabriel/oca/odoo/core/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/gabriel/oca/odoo/core/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/gabriel/oca/odoo/core/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/gabriel/oca/odoo/core/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "/home/gabriel/oca/odoo/core/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/gabriel/oca/odoo/core/odoo/addons/base/models/ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/gabriel/oca/odoo/core/odoo/addons/base/models/ir_module.py", line 593, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/gabriel/oca/odoo/core/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/gabriel/oca/odoo/core/odoo/modules/loading.py", line 459, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/gabriel/oca/odoo/core/odoo/modules/loading.py", line 347, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/gabriel/oca/odoo/core/odoo/modules/loading.py", line 240, in load_module_graph
    getattr(py_module, post_init)(cr, registry)
  File "/home/gabriel/oca/odoo/l10n-brazil/l10n_br_fiscal/hooks.py", line 77, in post_init_hook
    tools.convert_file(
  File "/home/gabriel/oca/odoo/core/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/gabriel/oca/odoo/core/odoo/tools/convert.py", line 778, in convert_xml_import
    doc = etree.parse(xmlfile)
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1880, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1900, in lxml.etree._parseFilelikeDocument
  File "src/lxml/parser.pxi", line 1795, in lxml.etree._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 1201, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gabriel/oca/odoo/core/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/gabriel/oca/odoo/core/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
  File "/home/gabriel/oca/odoo/l10n-brazil/l10n_br_fiscal/demo/company_demo.xml", line 14
lxml.etree.XMLSyntaxError: StartTag: invalid element name, line 14, column 6 ```

**Comment by marcos-mendez** [comment]
@llRedXD cara isto não esta na documentação e até agora não me foi instruido onde deveria ser colocado este tipo de informações porém já posso te ir adiantando que quebrei muito a cara por falta desta informação e só fui descobrir ao usar uma instância a qual reparei que o arquivo de configuração (O famoso ODOO.CONF) estava com o paramentro 

without_demo = False

mude este parametro para True e deverá ser corrigido o problema,

Não se esqueça de reiniciar o serviço do Odoo após esta modificação de configuração

Ou seja, você precisa definir para o Odoo que você não quer usar dados demo para que ele possa rodar o sistema.

O Porque da localização dar esse erro eu nunca entendi, mas como passa no RunBot e no Travis os PSC estão poco se lixando. 

A dica que te dou é, mude este parametro no odoo.conf. Se você não sabe aonde fica verifique a pasta /etc/odoo/odoo.conf ou as vezes ele pode ser colocado dentro da própria pasta do Odoo apesar de isto não ser uma boa prática nem no Linux nem na OCA. 

Espero que tenha ajudado, se você tiver dúvidas me procure t.me/inavigator eu não manjo muito mas no que eu puder ajudar estou a disposição abraços

**Comment by marcelsavegnago** [comment]
@llRedXD Por ora, se vc for subir uma instancia sem dados demo o correto é forçar isso usando o parametro --without-demo=all via odoo-bin ou já deixar configurado no odoo.conf without-demo=all conforme orientado pelo @marcos-mendez. 

De fato é uma limitação técnica necessária hoje.. Porém, quem tiver tempo e quiser explorar uma forma de tratar isso pode ter certeza que será muito bem vinda a ajuda.

E @llRedXD não precisa buscar diretamente uma pessoa especifica para te ajudar aqui não.. pode utilizar as Issues aqui do repositório (desta forma conseguimos manter as questões centralizadas, estas questões ficam disponiveis para outros colaboradores que podem se beneficiar da tua dúvida como coloaborar também). Se for o caso simplesmente adicione um ping para a pessoa que vc acredita que pode te ajudar.

**Comment by marcelsavegnago** [comment]
@marcos-mendez esta questão do without-demo está relacionado com isso aqui

https://github.com/OCA/l10n-brazil/blob/36ff03268439849d69ff46fa68ea5717903576f0/l10n_br_fiscal/hooks.py#L48

**Comment by marcelsavegnago** [comment]
Aqui tbm
https://github.com/OCA/l10n-brazil/blob/36ff03268439849d69ff46fa68ea5717903576f0/l10n_br_fiscal/hooks.py#L108

e aqui tbm

https://github.com/OCA/l10n-brazil/blob/36ff03268439849d69ff46fa68ea5717903576f0/l10n_br_fiscal/hooks.py#L162

**Comment by marcelsavegnago** [comment]
Este tipo de coisa auxilia na hora da instalação para deixar as demos mais enxutas. Sendo assim, as vezes o fato de ter que informar without-demo possa parecer algo ruim mas permite que outras coisas boas aconteçam como por exemplo o runbot conseguir subir as coisas mais rapidamente já que nao carrega todas as NCMs e afins..

**Comment by marcelsavegnago** [comment]
> E @llRedXD não precisa buscar diretamente uma pessoa especifica para te ajudar aqui não.. pode utilizar as Issues aqui do repositório (desta forma conseguimos manter as questões centralizadas, estas questões ficam disponiveis para outros colaboradores que podem se beneficiar da tua dúvida como coloaborar também). Se for o caso simplesmente adicione um ping para a pessoa que vc acredita que pode te ajudar.

@marcos-mendez e @llRedXD, só para reforçar a orientação..  Em cada módulo da OCA temos uma orientação sobre o relato de problemas e sobre o contato direto com colaboradores. É importante que quem estiver respondendo alguma dúvida não oriente nada diferente disso.

https://github.com/OCA/l10n-brazil/tree/12.0/l10n_br_account#bug-tracker
**_Bugs are tracked on GitHub Issues. In case of trouble, please check there if your issue has already been reported. If you spotted it first, help us smashing it by providing a detailed and welcomed feedback._**

**_Do not contact contributors directly about support or help with technical issues._**

cc @renatonlima @rvalyi @mileo

**Comment by llRedXD** [comment]
@marcelsavegnago  @marcos-mendez  Muito obrigado pela atenção e ajuda

**Comment by marcelsavegnago** [comment]
@llRedXD eu que agradeço.. Qualquer dúvida ou até mesmo colaboração(codigo,revisao, traducao e afins..) no projeto é bem vinda..

**Comment by marcelsavegnago** [comment]
@llRedXD se estiver tudo Ok e quiser fechar a Issue eu agradeço tbm :).. caso nao esteja.. dá um toque e vamos ajudando a medida do possível.
