### ISSUE TITLE
[BUG] data_credito na operação de retorno CNAB

### ISSUE THREAD

**Issue by antoniospneto** [OCA/l10n-brazil#1729]
Ao tentar fazer a operação de retorno no módulo brcobrança, as vezes estoura esse erro:

```
Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/custom/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 967, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 955, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/auto/addons/l10n_br_account_payment_brcobranca/wizard/import_statement.py", line 20, in import_statement
    ).multi_move_import(importer.input_statement, ftype.replace(".", ""))
  File "/opt/odoo/auto/addons/l10n_br_account_payment_brcobranca/models/account_journal.py", line 81, in multi_move_import
    for result_row_list in parser.parse(file_stream):
  File "/opt/odoo/auto/addons/l10n_br_account_payment_brcobranca/parser/cnab_file_parser.py", line 72, in parse
    self.result_row_list = self.process_return_file(data)
  File "/opt/odoo/auto/addons/l10n_br_account_payment_brcobranca/parser/cnab_file_parser.py", line 321, in process_return_file
    linha_cnab, account_move_line, bank_line
  File "/opt/odoo/auto/addons/l10n_br_account_payment_brcobranca/parser/cnab_file_parser.py", line 545, in _get_accounting_entries
    "real_payment_date": data_credito.strftime("%Y-%m-%d"),
AttributeError: 'str' object has no attribute 'strftime'
```

Deve ser algo simples de resolver, a noite eu vou mexer nisso, só tô abrindo aqui a issue para não esquecer.

**Comment by mbcosta** [comment]
@netosjb pelo LOG parece que por algum motivo o campo da data_credito está caindo aqui https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_account_payment_brcobranca/parser/cnab_file_parser.py#L373 você pode colocar um print('************ JSON Data Credito ***************', linha_cnab['data_credito']) antes do IF e ver o que está vindo do BRCobranca e um print('************ Data Credito ***************', data_credito) depois para saber o valor atribuído, pelo o que você comentou o seu caso de uso é o Itau CNAB400 o campo parece ser preenchido no BRCobranca https://github.com/kivanio/brcobranca/blob/master/lib/brcobranca/retorno/cnab400/itau.rb#L105 como é um pagamento deveria vir essa Data, bom pelo print vai ser possível descobrir o que está vindo e como o IF deve tratar a situação.

**Comment by antoniospneto** [comment]
Ok! obrigado pela dica @mbcosta ! 
logo a noite vou estar vendo isso e passo aqui meu feedback

**Comment by antoniospneto** [comment]
Desculpa, acabei de debugar e percebi que o erro era nas minhas parametrização do CNAB. o código está correto.
Valeu @mbcosta;
