### ISSUE TITLE
[BUG] Instalação do l10n_br_fiscal v14

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#1734]
Olá pessoal,

Ao instalar o l10n_br_fiscal na versão 14.0 obtive o seguinte problema:

ValueError: Chave de acesso invalida: '35200497231608000169550010000000371161029083' e tambem para a chave 26180812984794000154550010000016871192213339

Removi as mesmas dos dados de demonstração e funcional legal.

**Comment by mileo** [comment]
A propósito, não tive problemas com o XMLSEC como reportado em https://github.com/erpbrasil/erpbrasil.assinatura/pull/26

Com a seguinte configuração:

```
FROM camptocamp/odoo-project:14.0-latest-batteries

RUN apt-get update \
    && apt-get install -y --no-install-recommends nano wget git tig fonts-symbola libreoffice libsasl2-dev pkg-config libldap2-dev libxml2-dev libxmlsec1-openssl  libssl-dev vim wget git libxmlsec1-dev build-essential python3-dev locales swig3.0 python-setuptools  python-openssl \
    && apt-get clean  \
    && rm -rf /var/lib/apt/lists/*
```

```
num2words==0.5.4
pycep-correios==5.0.0
workalendar==7.1.1
erpbrasil.base==2.1.0
#erpbrasil.assinatura==1.2.0
erpbrasil.transmissao
#erpbrasil.edoc
erpbrasil.edoc.pdf
nfselib.ginfes==0.2.0
nfselib.issnet==0.2.0
xmldiff
lxml
-e git+https://github.com/erpbrasil/erpbrasil.edoc.git@master#egg=erpbrasil.edoc
-e git+https://github.com/erpbrasil/erpbrasil.assinatura.git@mileo-pytz#egg=erpbrasil.assinatura
-e git+https://github.com/akretion/nfelib.git@master_gen_v4_00#egg=nfelib
-e git+https://github.com/OCA/openupgradelib.git@master#egg=openupgradelib
-e git://github.com/erpbrasil/febraban-python.git@v0.7.1#egg=febraban
vcrpy
odoo-test-helper
```

**Comment by marcos-mendez** [comment]
Isso do v14 eh uma boa dica mileo brigado. Vou tentar chegando em casa. O
swig3.0 via apt get install neh?


Em dom, 28 de nov de 2021 13:59, Luis Felipe Miléo ***@***.***>
escreveu:

**Comment by marcelsavegnago** [comment]
> Isso do v14 eh uma boa dica mileo brigado. Vou tentar chegando em casa. O swig3.0 via apt get install neh?

Na verdade acho que não deu problema por conta da branch que o @mileo ta usando agora:
`-e git+https://github.com/erpbrasil/erpbrasil.assinatura.git@mileo-pytz#egg=erpbrasil.assinatura`

**Comment by marcos-mendez** [comment]
esse comando menos -e antes do git ele dá como not found pra mim tenho que
ver o que que é, também tem o fato de que é um dependencia né, não é
simplesemnte instalar ela. Vou ver como faço.

Em dom., 28 de nov. de 2021 às 16:21, Marcel Savegnago <
***@***.***> escreveu:

**Comment by marcelsavegnago** [comment]
> esse comando menos -e antes do git ele dá como not found pra mim tenho que ver o que que é, também tem o fato de que é um dependencia né, não é simplesemnte instalar ela. Vou ver como faço.

Então.. pip install -e .. 
deveria rodar.. 

Enfim, eu estava justamente subindo um ambiente v14 com a imagem da camptocamp e deu pau no erpbrasil.assinatura. Vou testar agora com esta instalação.

@mileo python 3.8 ou 3.7 ?

**Comment by marcelsavegnago** [comment]
Agora que vi que tem umas dependencias que o @mileo citou.. Vou testar novamente porque ainda estava dando pau no erpbrasil.assinatura

**Comment by marcos-mendez** [comment]
O erpbrasil.doc e o erpbrasil.assinatura estão comentados no requirements. É isso mesmo @mileo e @marcelsavegnago ?

**Comment by marcos-mendez** [comment]
> A propósito, não tive problemas com o XMLSEC como reportado em [erpbrasil/erpbrasil.assinatura#26](https://github.com/erpbrasil/erpbrasil.assinatura/pull/26)
> 
> Com a seguinte configuração:
> 
> ```
> FROM camptocamp/odoo-project:14.0-latest-batteries
> 
> RUN apt-get update \
>     && apt-get install -y --no-install-recommends nano wget git tig fonts-symbola libreoffice libsasl2-dev pkg-config libldap2-dev libxml2-dev libxmlsec1-openssl  libssl-dev vim wget git libxmlsec1-dev build-essential python3-dev locales swig3.0 python-setuptools  python-openssl \
>     && apt-get clean  \
>     && rm -rf /var/lib/apt/lists/*
> ```
> 
> ```
> num2words==0.5.4
> pycep-correios==5.0.0
> workalendar==7.1.1
> erpbrasil.base==2.1.0
> #erpbrasil.assinatura==1.2.0
> erpbrasil.transmissao
> #erpbrasil.edoc
> erpbrasil.edoc.pdf
> nfselib.ginfes==0.2.0
> nfselib.issnet==0.2.0
> xmldiff
> lxml
> -e git+https://github.com/erpbrasil/erpbrasil.edoc.git@master#egg=erpbrasil.edoc
> -e git+https://github.com/erpbrasil/erpbrasil.assinatura.git@mileo-pytz#egg=erpbrasil.assinatura
> -e git+https://github.com/akretion/nfelib.git@master_gen_v4_00#egg=nfelib
> -e git+https://github.com/OCA/openupgradelib.git@master#egg=openupgradelib
> -e git://github.com/erpbrasil/febraban-python.git@v0.7.1#egg=febraban
> vcrpy
> odoo-test-helper
> ```

@mileo segui as recomendações que você colocou aqui, e instalei o pip e. 

Apesar de não ter travado tanto quando instalo tipo -i l10n_br_fiscal ou quando faço pela interface ainda tenho este erro aqui bem no meio da instalação. 

`Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-72>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 593, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 461, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 349, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 780, in convert_xml_import
    relaxng = etree.RelaxNG(etree.parse(schema))
  File "src/lxml/etree.pyx", line 3435, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1840, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1866, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1770, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1163, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 651, in lxml.etree._raiseParseError
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
  File "b'/usr/lib/python3/dist-packages/odoo/import_xml.rng'", line 0
lxml.etree.XMLSyntaxError: <no detail available>`

O que acho estranho é que é um erro do Odoo e não da localização. então não sei ao certo o que pode ser o problema.

Outra coisa que tentei testar foi isso de remover as tais chaves que você disse, mas não encontrei aonde remove-las.

qualquer coisa fico a disposição para testar mais coisas. 
VLW obrigado

**Comment by antoniospneto** [comment]
> Olá pessoal,
> 
> Ao instalar o l10n_br_fiscal na versão 14.0 obtive o seguinte problema:
> 
> ValueError: Chave de acesso invalida: '35200497231608000169550010000000371161029083' e tambem para a chave 26180812984794000154550010000016871192213339
> 
> Removi as mesmas dos dados de demonstração e funcional legal.

Aconteceu o mesmo comigo, tem que atualizar o erpbrasil.base de 2.1.0 para 2.2.2. isso resolveu para mim.

**Comment by rvalyi** [comment]
Vou fechar o issue então e reabrimos caso ainda fosse necessário.
