### ISSUE TITLE
[BUG]12.0 - Update l10n_br_fiscal: error in migration script 

### ISSUE THREAD

**Issue by vanderleiromera** [OCA/l10n-brazil#1862]
Erro relacionado ao PR #1810 

 -- Ao excecutar update no l10n_br_fiscal, recebo esse erro:

2022-04-06 19:35:33,059 188331 INFO eipparana odoo.modules.migration: module l10n_br_fiscal: Running migration [>12.0.24.0.0] pre-migration 
2022-04-06 19:35:33,420 188331 INFO eipparana OpenUpgrade: l10n_br_fiscal: pre-migration script called with version 12.0.23.0.0 
2022-04-06 19:35:33,685 188331 ERROR eipparana OpenUpgrade: l10n_br_fiscal: error in migration script l10n_br_fiscal/migrations/12.0.24.0.0/pre-migration.py: Invalid field 'icms_origin' in leaf "<osv.ExtendedLeaf: ('icms_origin', '!=', False) on product_template (ctx: )>" 
2022-04-06 19:35:33,686 188331 ERROR eipparana OpenUpgrade: Invalid field 'icms_origin' in leaf "<osv.ExtendedLeaf: ('icms_origin', '!=', False) on product_template (ctx: )>" 
Traceback (most recent call last):
  File "/home/vanderlei/Projects/odoo12/odoo-venv/src/openupgradelib/openupgradelib/openupgrade.py", line 1876, in wrapped_function
    if use_env2 else cr, version)
  File "/home/vanderlei/Projects/odoo12/l10n-brazil/l10n_br_fiscal/migrations/12.0.24.0.0/pre-migration.py", line 19, in migrate
    ("icms_origin", "!=", False),
  File "/home/vanderlei/Projects/odoo12/core/odoo/models.py", line 1581, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/vanderlei/Projects/odoo12/core/odoo/models.py", line 4149, in _search
    query = self._where_calc(args)
  File "/home/vanderlei/Projects/odoo12/core/odoo/models.py", line 3941, in _where_calc
    e = expression.expression(domain, self)
  File "/home/vanderlei/Projects/odoo12/core/odoo/osv/expression.py", line 677, in __init__
    self.parse()
  File "/home/vanderlei/Projects/odoo12/core/odoo/osv/expression.py", line 858, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'icms_origin' in leaf "<osv.ExtendedLeaf: ('icms_origin', '!=', False) on product_template (ctx: )>"
2022-04-06 19:35:33,717 188331 WARNING eipparana odoo.modules.loading: Transient module states were reset 
2022-04-06 19:35:33,718 188331 ERROR eipparana odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/home/vanderlei/Projects/odoo12/core/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/vanderlei/Projects/odoo12/core/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/vanderlei/Projects/odoo12/core/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/vanderlei/Projects/odoo12/core/odoo/modules/loading.py", line 177, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/vanderlei/Projects/odoo12/core/odoo/modules/migration.py", line 190, in migrate_module
    migrate(self.cr, installed_version)
  File "/home/vanderlei/Projects/odoo12/odoo-venv/src/openupgradelib/openupgradelib/openupgrade.py", line 1876, in wrapped_function
    if use_env2 else cr, version)
  File "/home/vanderlei/Projects/odoo12/l10n-brazil/l10n_br_fiscal/migrations/12.0.24.0.0/pre-migration.py", line 19, in migrate
    ("icms_origin", "!=", False),
  File "/home/vanderlei/Projects/odoo12/core/odoo/models.py", line 1581, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/vanderlei/Projects/odoo12/core/odoo/models.py", line 4149, in _search
    query = self._where_calc(args)
  File "/home/vanderlei/Projects/odoo12/core/odoo/models.py", line 3941, in _where_calc
    e = expression.expression(domain, self)
  File "/home/vanderlei/Projects/odoo12/core/odoo/osv/expression.py", line 677, in __init__
    self.parse()
  File "/home/vanderlei/Projects/odoo12/core/odoo/osv/expression.py", line 858, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'icms_origin' in leaf "<osv.ExtendedLeaf: ('icms_origin', '!=', False) on product_template (ctx: )>"
2022-04-06 19:35:33,719 188331 CRITICAL eipparana odoo.service.server: Failed to initialize database `eipparana`. 
Traceback (most recent call last):
  File "/home/vanderlei/Projects/odoo12/core/odoo/service/server.py", line 1164, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/vanderlei/Projects/odoo12/core/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/vanderlei/Projects/odoo12/core/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/vanderlei/Projects/odoo12/core/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/vanderlei/Projects/odoo12/core/odoo/modules/loading.py", line 177, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/vanderlei/Projects/odoo12/core/odoo/modules/migration.py", line 190, in migrate_module
    migrate(self.cr, installed_version)
  File "/home/vanderlei/Projects/odoo12/odoo-venv/src/openupgradelib/openupgradelib/openupgrade.py", line 1876, in wrapped_function
    if use_env2 else cr, version)
  File "/home/vanderlei/Projects/odoo12/l10n-brazil/l10n_br_fiscal/migrations/12.0.24.0.0/pre-migration.py", line 19, in migrate
    ("icms_origin", "!=", False),
  File "/home/vanderlei/Projects/odoo12/core/odoo/models.py", line 1581, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/vanderlei/Projects/odoo12/core/odoo/models.py", line 4149, in _search
    query = self._where_calc(args)
  File "/home/vanderlei/Projects/odoo12/core/odoo/models.py", line 3941, in _where_calc
    e = expression.expression(domain, self)
  File "/home/vanderlei/Projects/odoo12/core/odoo/osv/expression.py", line 677, in __init__
    self.parse()
  File "/home/vanderlei/Projects/odoo12/core/odoo/osv/expression.py", line 858, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'icms_origin' in leaf "<osv.ExtendedLeaf: ('icms_origin', '!=', False) on product_template (ctx: )>"
2022-04-06 19:35:33,721 188331 INFO eipparana odoo.service.server: Stopping gracefully

**Comment by vanderleiromera** [comment]
Passando parâmetro " -i ", funciona a migração, porém limpa os respectivos campos ...
![Screenshot from 2022-04-07 10-24-12](https://user-images.githubusercontent.com/65144026/162240157-b6757e18-2b8e-47fa-9cfc-a8b053cb47fc.png)

**Comment by rvalyi** [comment]
confirmando esse bug... Logo eu vou propor um fix ou um workaround...

**Comment by rvalyi** [comment]
resolvido por https://github.com/OCA/l10n-brazil/pull/1890 valeu por reportar!
