### ISSUE TITLE
[14.0] l10n_br_hr: problema quando o gestor do colaborador tenta aprovar o relatório de despesa

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1980]
![image](https://user-images.githubusercontent.com/3595132/173377665-c865a211-3eef-48d0-b580-e15efdf90bbf.png)

https://github.com/odoo/odoo/blob/30a3f582217835945e38220451574d49baabe4f1/addons/hr_expense/models/hr_expense.py#L941

https://github.com/odoo/odoo/blob/30a3f582217835945e38220451574d49baabe4f1/addons/hr/models/hr_employee.py#L135

cc @renatonlima @rvalyi @mileo @douglascstd

**Comment by douglascstd** [comment]
No runboat da OCA, para repetir o problema:
1- Criar usuário _manager_ e habilitar "Aprovador"
2- Selecionar o _manager_ como aprovador de Relatórios de despesa
3- Entrar como _manager_, e fazer aprovação do relatório
4- Erro é apresentado

Screenshots:
1
![image](https://user-images.githubusercontent.com/20867090/173916306-6de2fb17-6f0a-4b20-8d7f-33c81a18b342.png)

2
![image](https://user-images.githubusercontent.com/20867090/173916557-3517675e-a880-4b47-b082-1b09e19cbc84.png)

3
![image](https://user-images.githubusercontent.com/20867090/173916706-bb3dbfa7-247f-48e4-ba89-4be805d288e5.png)

4
![image](https://user-images.githubusercontent.com/20867090/173916842-df2a4c52-24f1-45d0-a96c-a3e66077911b.png)


**Error:**
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 1398, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 1386, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/hr_expense/models/hr_expense.py", line 941, in approve_expense_sheets
    current_managers = self.employee_id.expense_manager_id | self.employee_id.parent_id.user_id | self.employee_id.department_id.manager_id.user_id
  File "/opt/odoo/odoo/fields.py", line 2485, in __get__
    return super().__get__(records, owner)
  File "/opt/odoo/odoo/fields.py", line 998, in __get__
    recs._fetch_field(self)
  File "/opt/odoo/odoo/models.py", line 3071, in _fetch_field
    self._read(fnames)
  File "/opt/odoo/addons/hr/models/hr_employee.py", line 135, in _read
    res = self.env['hr.employee.public'].browse(self.ids).read(fields)
  File "/opt/odoo/odoo/models.py", line 3011, in read
    raise ValueError("Invalid field %r on model %r" % (name, self._name))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field 'cnpj_cpf' on model 'hr.employee.public'

**Comment by mileo** [comment]
@ygcarvalh pode dar uma olhada?

**Comment by marcelsavegnago** [comment]
Acredito que este assunto já foi resolvido. Se alguem puder testar eu agradeço.

@WesleyOliveira98 @Matthwhy

**Comment by WesleyOliveira98** [comment]
> Acredito que este assunto já foi resolvido. Se alguem puder testar eu agradeço.

@marcelsavegnago teste ok, pode encerrar
![image](https://github.com/user-attachments/assets/5962dfd5-e545-4dad-9e1c-b3c5d7fc2b4a)
