### ISSUE TITLE
l10n-brazil/l10n_br_fiscal/demo/product_demo.xml:512, near <record id="product.product_product_4d" model="product.product">

### ISSUE THREAD

**Issue by beneditomonteiro** [OCA/l10n-brazil#1993]
## Module
Fiscal localização Brazil

## Describe the bug
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo14_comm/odoo/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/opt/odoo14_comm/odoo/odoo/tools/convert.py", line 530, in _tag_record
    raise Exception("Cannot update missing record %r" % xid)
Exception: Cannot update missing record 'product.product_product_4d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo14_comm/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo14_comm/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo14_comm/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo14_comm/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo14_comm/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo14_comm/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo14_comm/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo14_comm/odoo/addons/web/controllers/main.py", line 1398, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo14_comm/odoo/addons/web/controllers/main.py", line 1386, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo14_comm/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo14_comm/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-72>", line 2, in button_immediate_install
  File "/opt/odoo14_comm/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo14_comm/odoo/odoo/addons/base/models/ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo14_comm/odoo/odoo/addons/base/models/ir_module.py", line 593, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo14_comm/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo14_comm/odoo/odoo/modules/loading.py", line 459, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo14_comm/odoo/odoo/modules/loading.py", line 347, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo14_comm/odoo/odoo/modules/loading.py", line 240, in load_module_graph
    getattr(py_module, post_init)(cr, registry)
  File "/opt/odoo14_comm/custom_addons/l10n-brazil/l10n_br_fiscal/hooks.py", line 81, in post_init_hook
    tools.convert_file(
  File "/opt/odoo14_comm/odoo/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/opt/odoo14_comm/odoo/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/opt/odoo14_comm/odoo/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/opt/odoo14_comm/odoo/odoo/tools/convert.py", line 681, in _tag_root
    raise ParseError('while parsing %s:%s, near\n%s' % (
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo14_comm/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo14_comm/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /opt/odoo14_comm/custom_addons/l10n-brazil/l10n_br_fiscal/demo/product_demo.xml:512, near
<record id="product.product_product_4d" model="product.product">
        <field name="ncm_id" ref="l10n_br_fiscal.ncm_94033000"/>
        <field name="fiscal_genre_id" ref="l10n_br_fiscal.product_genre_94"/>
        <field name="fiscal_type">04</field>
        <field name="icms_origin">0</field>
    </record>

## To Reproduce
Odoo 14

1. Clicar em instalar Fiscal Brazil

**Expected behavior**
Concluir a instalação da localização Brasileira.

**Additional context**

**Comment by igorpita** [comment]
Algum paliativo para esse erro na instalação do módulo fiscal ?

**Comment by rvalyi** [comment]
Ola @igorpita , atualize o seu clone do OCA/l10n-brazil porque esse problema (e muitos outros) já foi solucionado 6 meses atras come essa mudança:
https://github.com/OCA/l10n-brazil/commit/c117146244535f7526c6cc2924357d56cbe3a302
Isso foi uma regressão porque os caras da Odoo SA simplesmente removeram esse produto dos dados de demo (porque não nè):
https://github.com/OCA/l10n-brazil/pull/2175#issuecomment-1285564718
https://github.com/odoo/odoo/commit/ab1d7caefa910197579b12ae934fb572f9cff50d

depois de atualizar, da um restart com a opção --update=all
