### ISSUE TITLE
[14.0][BUG] Problema ao faturar um contrato com para produto

### ISSUE THREAD

**Issue by douglascstd** [OCA/l10n-brazil#2021]
Falha ao criar faturas de contratos onde o produto é serviço (Fiscal Type=service)
Apresenta o problema ao criar fatura:
**Error:**
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 1398, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 1386, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/mnt/data/odoo-addons-dir/l10n_br_contract/models/contract_contract.py", line 164, in recurring_create_invoice
    invoices = self._recurring_create_invoice()
  File "/mnt/data/odoo-addons-dir/l10n_br_contract/models/contract_contract.py", line 90, in _recurring_create_invoice
    moves = super()._recurring_create_invoice(date_ref)
  File "/opt/odoo-venv/lib/python3.6/site-packages/odoo/addons/contract/models/contract.py", line 595, in _recurring_create_invoice
    invoices_values = self._prepare_recurring_invoices_values(date_ref)
  File "/mnt/data/odoo-addons-dir/l10n_br_contract/models/contract_contract.py", line 130, in _prepare_recurring_invoices_values
    self.company_id
  File "/mnt/data/odoo-addons-dir/l10n_br_fiscal/models/operation_line.py", line 155, in get_document_type
    self.ensure_one()
  File "/opt/odoo/odoo/models.py", line 5014, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Expected singleton: l10n_br_fiscal.operation.line()

## To Reproduce
É possível reproduzir no RunBoat da OCA
>l10n-brazil>contract

1-Criar produto do tipo Serviço
![image](https://user-images.githubusercontent.com/20867090/179216786-4b581027-4359-4b23-a28d-44cc5c53d6c5.png)

2- Criar contrato e selecionar o produto serviço criado:
![image](https://user-images.githubusercontent.com/20867090/179216870-84153a1a-e5c7-4591-bb51-2316bf45fb9a.png)

3- Acionar o botão "Create invoices"

4- Apresentado o problema:
![image](https://user-images.githubusercontent.com/20867090/179217106-a4617a4b-86d4-45e7-ae0d-839e0c4c666a.png)

**Comment by marcelsavegnago** [comment]
@douglascstd neste caso o sistema está esperando receber uma linha de operação fiscal e não recebeu nenhum. Isto normalmente pode ser que a operacao fiscal está em modo rascunho, ou os filtros da linha da operacao fiscal não permitem a definição de uma linha de operacao fiscal na linha do contrato.

A PR #2020 visa facilitar a identificação de problemas deste tipo.

**Comment by douglascstd** [comment]
Funciona confirme esperado.
