### ISSUE TITLE
[14.0] l10n_br_portal ao instalar com without_demo=True

### ISSUE THREAD

**Issue by marcos-mendez** [OCA/l10n-brazil#2121]
Ao tentar instalar o modulo l10n_br_portal com o parametro without_demo=true no odoo Conf o seguinte erro é gerado na v14.0

## Module
l10n_br_portal

Erro gerado
```
2022-09-09 23:22:18,098 34531 INFO kimenz-prod odoo.modules.loading: loading l10n_br_portal/demo/res_users_demo.xml 
2022-09-09 23:22:18,100 34531 WARNING kimenz-prod odoo.modules.loading: Module l10n_br_portal demo data failed to install, installed without demo data 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7fa11a6f5950>, 'l10n_br_base.res_partner_kmee')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 564, in _tag_record
    f_val = self.id_get(f_ref)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 660, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 666, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_model.py", line 1938, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-36>", line 2, in xmlid_lookup
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_model.py", line 1931, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: l10n_br_base.res_partner_kmee

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 86, in load_demo
    load_data(cr, idref, mode, kind='demo', package=package)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 685, in _tag_root
    )) from e
odoo.tools.convert.ParseError: while parsing /usr/lib/python3/dist-packages/odoo/custom-addons/l10n-brazil/l10n_br_portal/demo/res_users_demo.xml:10, near
<record id="demo_user_kmee" model="res.users" context="{'no_reset_password': True}">
            <field name="partner_id" ref="l10n_br_base.res_partner_kmee"/>
            <field name="login">kmee</field>
            <field name="password">kmee</field>
            <field name="signature">&lt;span&gt;-- &lt;br/&gt;KMEE Demo Portal&lt;/span&gt;</field>
            <field name="groups_id" eval="[(5,)]"/><!-- Avoid auto-including this user in any default group -->
        </record>

```

**Comment by antoniospneto** [comment]
@marcos-mendez pelo log o módulo está carregando os dados demo sim, o correto não seria utilizar o --without-demo=all ?

**Comment by marcos-mendez** [comment]
Rsrs nunca testei com all a vida toda usei o True. Mas beleza vou testar qlq coisa fexo aqui vlw neto

**Comment by marcos-mendez** [comment]
Eu abri pq nao tenho como testar no runbot sem demo

**Comment by marcelsavegnago** [comment]
`ValueError: External ID not found in the system: l10n_br_base.res_partner_kmee`


Veja que o erro ocorre porque nao acha o parceiro res_partner_kmee que eh um dado demo.

**Comment by antoniospneto** [comment]
o módulo l10n_br_base foi instalado sem os dados demo e agora o l10n_br_portal está tentando instalar com os dados de demonstração, mas sem os dados demo do l10n_br_base dá erro.. tem que revisar o comando de instalação ou a configuração do odoo conf pois o comando  without_demo parece que não foi atendido..

**Comment by renan-prometheus-arch** [comment]
nano -l /opt/odoo14/odoo/addons/l10n_br_account_nfe/hooks.py 

def post_init_hook(cr, registry):
 9     env = api.Environment(cr, SUPERUSER_ID, {})
10 #    load_simples_nacional_demo(env, registry)
