### ISSUE TITLE
[14.0] l10n_br_account: Regressão envolvendo o fiscal operation type

### ISSUE THREAD

**Issue by antoniospneto** [OCA/l10n-brazil#2144]
Galera, a minha pr #2131 causou uma regressão. impede a visualização de move que não é uma fatura.
logo a noite subo um fix para isso, vou por uma tratamento para pular a verificação quando move for do tipo "**entry**"

>   File "/opt/odoo/auto/addons/l10n_br_account/models/account_invoice.py", line 122, in _compute_fiscal_operation_type
>     inv.fiscal_operation_type = MOVE_TO_OPERATION[inv.move_type]
> Exception
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/opt/odoo/custom/src/odoo/odoo/http.py", line 639, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/opt/odoo/custom/src/odoo/odoo/http.py", line 315, in _handle_exception
>     raise exception.with_traceback(None) from new_cause
> KeyError: 'entry'

**Comment by antoniospneto** [comment]
feito: #2145
