### ISSUE TITLE
[14.0] Exception: Cannot update missing record 'l10n_br_base.lucro_presumido_partner'

### ISSUE THREAD

**Issue by aleprovencio** [OCA/l10n-brazil#2172]
## Module

l10n_br_account, l10n_br_fiscal

## Describe the bug

Oi pessoal, ao final da instalação dos módulos em questão estou tendo este erro (Traceback abaixo). `Exception: Cannot update missing record 'l10n_br_base.lucro_presumido_partner'`

Estou usando o `odoo v14.0` via `docker` com a imagem oficial. Adicionei o `l10n-brazil` e as dependências `OCA` (sempre usando os branches `14`) e instalei o `requirements.txt` conforme o [guia de instalação](https://github.com/OCA/l10n-brazil/wiki/Instalando-o-Odoo-12--com-a-Localiza%C3%A7%C3%A3o-Brasileira). Cheguei também a adicionar mais dependências `OCA` conforme o `oca_dependencies.txt` deste repositório.

Consegui instalar normalmente os módulos `l10n_br_base` e `l10n_br_zip`.

Tenho dúvidas também se existe uma sequência correta de instalação, perdi alguma informação?

## Full error

```python
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 530, in _tag_record
    raise Exception("Cannot update missing record %r" % xid)
Exception: Cannot update missing record 'l10n_br_base.lucro_presumido_partner'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-72>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 593, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 461, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 349, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 240, in load_module_graph
    getattr(py_module, post_init)(cr, registry)
  File "/mnt/extra-addons/l10n-brazil/l10n_br_fiscal/hooks.py", line 88, in post_init_hook
    kind="demo",
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 685, in _tag_root
    )) from e
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /mnt/extra-addons/l10n-brazil/l10n_br_fiscal/demo/company_demo.xml:14, near
<record id="l10n_br_base.lucro_presumido_partner" model="res.partner">
        <field name="fiscal_profile_id" ref="l10n_br_fiscal.partner_fiscal_profile_cnt"/>
    </record>
```

**Comment by vanderleiromera** [comment]
Base sem usuário demo? se for ver se o conf esta assim:
     without_demo = all

**Comment by antoniospneto** [comment]
Acredito que o módulo l10n_base foi instalado sem os dados de demonstração, pode ser que na instalação ocorreu um erro e o carregamento dos dados demos foram interrompidos, esse tipo de erro não impede a instalação do módulo, o módulo l10n_base será instalado porém sem os dados de demonstração.

Porém quando você instalar um próximo módulo que depende dos dados demonstração do módulo l10n_base, que é o caso do l10n_br_account, l10n_br_fiscal vai acontecer o erro que você postou.

Minha dica:

1) Apague a banco de dados atual e inicie uma base nova limpa.
2) Instale primeiro o módulo l10n_br_base, acompanhe no log se a instalação foi feita com sucesso sem nenhum erro, se houver falha no carregamento dos dados será exibido no log, se ocorrer veja na descrição qual foi a causa.
3) Instale depois o l10n_br_account e confira se deu tudo certo. 

Obs:
Estou partindo da permissa que você deseja uma instalação com os dados de demonstração.
Se esse é o caso a configuração do seu Odoo não pode ter o parâmetro "without_demo = all"
nem mesmo usar o  --without-demo=all na instalação dos módulos via linha de comando.

**Comment by aleprovencio** [comment]
Primeiramente, obrigado pelas prontas respostas!

Em meus testes eu estou usando este [odoo.conf](https://github.com/odoo/docker/blob/master/14.0/odoo.conf) que é o padrão da imagem oficial docker, aonde não há a configuração `without_demo` então acredito estar usando o default. Até então havia alterado neste arquivo apenas o `addons_path` para incluir os módulos.

Nestes testes eu também estou fazendo tudo pela interface web e não pela linha de comando, então quando quero dados de demonstração seto a opção `Demo Data` ao criar um novo banco. Algo que também não sabia e percebi nos testes, é que dependendo se criei ou não o banco com `Demo Data`, o mesmo servirá para os módulos a serem instalados via interface.

A princípio a instalação do `l10n_br_account` não funcionava com ou sem dados de demonstração, mas percebi que quando os incluía, me foi apontado este novo erro:
`WARNING ? odoo.service.server: Thread <Thread(odoo.service.http.request.139636391257856, started 139636391257856)> virtual real time limit (151/120s) reached.`

Dando uma pesquisada achei esta outra [thread aqui](https://github.com/OCA/l10n-brazil/issues/1609) falando disso, atualizei meu `odoo.conf` seguindo a orientação. Criei uma nova base com dados de demonstração e a instalação funcionou! :partying_face:

Contudo fiz um novo teste com estas mesmas modificações no `odoo.conf` mas agora sem os dados de demonstração, e o erro inicial desta issue ocorreu novamente.

Então minha dúvida é, os dados de demonstração são necessários para a instalação destes módulos? Se sim como proceder em ambiente de produção?

**Comment by antoniospneto** [comment]
@aleprovencio para o ambiente de produção não se deve instalar os dados de demostração, você deve desabilitar a opção do demo data na criação do banco de dados.

Não sou muito acostumado a iniciar uma base pelo modo gráfico, mas se for por linha de comando você deve setar no odoo conf o parametro "without_demo = all" conforme o @vanderleiromera comentou.

**Comment by aleprovencio** [comment]
Após novos testes confirmei que usar `without_demo = all` no arquivo de configuração é o suficiente para instalar com sucesso os módulos sem os dados de demonstração via interface gráfica.

Muito grato pela ajuda :)
