### ISSUE TITLE
[14.0] l10n_br_stock - migração - stock.picking não existe

### ISSUE THREAD

**Issue by vanderleiromera** [OCA/l10n-brazil#2174]
Ao atualizar db recebo esse erro....

```
2022-10-19 22:39:44,984 1 INFO prod odoo.modules.loading: Loading module l10n_br_stock (45/60) 
2022-10-19 22:39:45,115 1 INFO prod odoo.modules.migration: module l10n_br_stock: Running migration [>14.0.2.0.0] pre-migration 
2022-10-19 22:39:45,340 1 INFO prod OpenUpgrade: l10n_br_stock: pre-migration script called with version 14.0.1.0.0 
2022-10-19 22:39:45,340 1 INFO prod OpenUpgrade: table stock.picking, column ie: renaming to inscr_est 
2022-10-19 22:39:45,341 1 ERROR prod odoo.sql_db: bad query: ALTER TABLE "stock.picking" RENAME "ie" TO "inscr_est"
ERROR: relation "stock.picking" does not exist
 
2022-10-19 22:39:45,341 1 ERROR prod OpenUpgrade: l10n_br_stock: error in migration script l10n_br_stock/migrations/14.0.2.0.0/pre-migration.py: relation "stock.picking" does not exist
 
2022-10-19 22:39:45,341 1 ERROR prod OpenUpgrade: relation "stock.picking" does not exist
 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/openupgradelib/openupgrade.py", line 2042, in wrapped_function
    func(
  File "/opt/odoo/auto/addons/l10n_br_stock/migrations/14.0.2.0.0/pre-migration.py", line 14, in migrate
    openupgrade.rename_columns(env.cr, _column_renames)
  File "/usr/local/lib/python3.8/site-packages/openupgradelib/openupgrade.py", line 575, in rename_columns
    cr.execute(
  File "<decorator-gen-3>", line 2, in execute
  File "/opt/odoo/custom/src/odoo/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/sql_db.py", line 300, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedTable: relation "stock.picking" does not exist

2022-10-19 22:39:45,346 1 WARNING prod odoo.modules.loading: Transient module states were reset 
2022-10-19 22:39:45,369 1 ERROR prod odoo.modules.registry: Failed to load registry 
2022-10-19 22:39:45,370 1 ERROR prod click_odoo.env_options: exception 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/click_odoo/env_options.py", line 191, in _invoke
    with self.environment_manager(
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/click_odoo_contrib/update.py", line 284, in OdooEnvironmentWithUpdate
    _update_db(
  File "/usr/local/lib/python3.8/site-packages/click_odoo_contrib/update.py", line 255, in _update_db
    _update_db_nolock(
  File "/usr/local/lib/python3.8/site-packages/click_odoo_contrib/update.py", line 233, in _update_db_nolock
    Registry.new(database, update_module=True)
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 455, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 347, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 174, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/opt/odoo/custom/src/odoo/odoo/modules/migration.py", line 180, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.8/site-packages/openupgradelib/openupgrade.py", line 2042, in wrapped_function
    func(
  File "/opt/odoo/auto/addons/l10n_br_stock/migrations/14.0.2.0.0/pre-migration.py", line 14, in migrate
    openupgrade.rename_columns(env.cr, _column_renames)
  File "/usr/local/lib/python3.8/site-packages/openupgradelib/openupgrade.py", line 575, in rename_columns
    cr.execute(
  File "<decorator-gen-3>", line 2, in execute
  File "/opt/odoo/custom/src/odoo/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/sql_db.py", line 300, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedTable: relation "stock.picking" does not exist

Error: relation "stock.picking" does not exist

```

**Comment by rvalyi** [comment]
O módulo stock está instalado? Talvez vc deveria instalar ele antes da tentar atualizar.

**Comment by vanderleiromera** [comment]
puts, ato falho, foi mal ...vacilei aqui

**Comment by antoniospneto** [comment]
Pessoal tem uma falha no script não? o nome do modelo é stock.picking mas a tabela é **stock_picking**

Acho que passou despercebido ao fazer o script

@mbcosta @rvalyi @vanderleiromera

**Comment by vanderleiromera** [comment]
Então, estava ciente que já tinha o stock instalado, mas ao instalar novamente, e executar o update atualizou,  já tinha tentado fazer a migração de um db da 12 > 14, e  falhou nesse mesmo upgrade da 13 > 14, vou tester nessa migração ...

**Comment by vanderleiromera** [comment]
#2175
