### ISSUE TITLE
[14.0][BUG] Problema com o modulo PIX

### ISSUE THREAD

**Issue by marcos-mendez** [OCA/l10n-brazil#2255]
```2022-12-13 01:38:31,756 151890 INFO kimenz-prod odoo.addons.base.models.ir_ui_view: O campo "partner_pix_id" não existe no modelo "account.payment.line"

View name: l10n_br_account_payment_order.payment.line.form
Error context:
 view: ir.ui.view(4057,)
 xmlid: l10n_br_account_payment_order_payment_line_form
 view.model: account.payment.line
 view.parent: ir.ui.view(4041,)
 file: /usr/lib/python3/dist-packages/odoo/custom-addons/l10n-brazil/l10n_br_account_payment_order/views/account_payment_line.xml
 
2022-12-13 01:38:31,762 151890 WARNING kimenz-prod odoo.modules.loading: Transient module states were reset 
2022-12-13 01:38:31,767 151890 ERROR kimenz-prod odoo.modules.registry: Failed to load registry 
2022-12-13 01:38:31,768 151890 ERROR kimenz-prod odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4220, in _load_records
    data['record']._load_records_write(data['values'])
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1851, in _load_records_write
    super(View, self)._load_records_write(values)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4149, in _load_records_write
    self.write(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/theme_models.py", line 293, in write
    res = super(IrUiView, other_views).write(vals)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 68, in write
    return super(View, self).write(vals)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 500, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3703, in write
    fields[0].determine_inverse(real_recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1187, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 300, in _inverse_arch
    view.write(data)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/theme_models.py", line 293, in write
    res = super(IrUiView, other_views).write(vals)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 68, in write
    return super(View, self).write(vals)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 500, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3693, in write
    real_recs._validate_fields(vals, inverse_fields)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1266, in _validate_fields
    check(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 411, in _check_xml
    )).with_traceback(e.__traceback__) from None
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 391, in _check_xml
    view.postprocess_and_fields(view_doc, validate=True)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 850, in postprocess_and_fields
    arch, name_manager = self._postprocess_view(node, model, validate=validate)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 862, in _postprocess_view
    self.postprocess(node, [], editable, name_manager)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 962, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 962, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 962, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 953, in postprocess
    validator(node, name_manager, node_info)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1089, in _validate_tag_field
    self.handle_view_error(msg)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 673, in handle_view_error
    raise ValueError(formatted_message).with_traceback(from_traceback) from from_exception
odoo.exceptions.ValidationError: Erro ao validar a visualização:

O campo "partner_pix_id" não existe no modelo "account.payment.line"

View name: l10n_br_account_payment_order.payment.line.form
Error context:
 view: ir.ui.view(4057,)
 xmlid: l10n_br_account_payment_order_payment_line_form
 view.model: account.payment.line
 view.parent: ir.ui.view(4041,)
 file: /usr/lib/python3/dist-packages/odoo/custom-addons/l10n-brazil/l10n_br_account_payment_order/views/account_payment_line.xml


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1394, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1382, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-78>", line 2, in button_immediate_upgrade
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 654, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 593, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 457, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 349, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 685, in _tag_root
    )) from e
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /usr/lib/python3/dist-packages/odoo/custom-addons/l10n-brazil/l10n_br_account_payment_order/views/account_payment_line.xml:9, near
<record id="l10n_br_account_payment_order_payment_line_form" model="ir.ui.view">
        <field name="name">l10n_br_account_payment_order.payment.line.form</field>
        <field name="model">account.payment.line</field>
        <field name="priority">99</field>
        <field name="inherit_id" ref="account_payment_order.account_payment_line_form"/>
        <field name="arch" type="xml">
            <data><!-- TODO Campos não podem ser alterados aqui, o account.move.line ficaria
                  diferente, verificar no caso de Pagtos/outbound, principalmente se o
                  programa irá permitir cadastrar Ordens de Pagto diretamente sem
                  um "documento de origem" ( parece ser melhor não, p/ evitar
                  inconsistencias ). E qual seria o sentido de fazer uma Ordem de
                  Pagto sem relação com uma Fatura ou Lançamento ? Isso não
                  acabaria gerando um registro avulso sem relação com nada, apenas com
                   a necessidade de ter um arquivo, quais seriam os casos de uso ? -->
            <field name="amount_currency" position="attributes">
                <attribute name="attrs">{'readonly': [('payment_method_code', 'in', ('400', '240', '500'))]}</attribute>
            </field>

            <!-- TODO: Implementação de Títulos com Diferentes Moedas,
                  CNAB 240 parece permitir -->
            <field name="currency_id" position="attributes">
                <attribute name="attrs">{'readonly': [('payment_method_code', 'in', ('400', '240', '500'))]}</attribute>

            </field>

            <!-- TODO: Existe necessidade de alteração desse campo aqui ? Qual caso de uso ? -->
            <field name="move_line_id" position="attributes">
                  <attribute name="attrs">{'readonly': [('payment_method_code', 'not in', ('400', '240', '500'))]}</attribute>
            </field>

            <field name="move_line_id" position="before">
                <field name="move_id" attrs="{'readonly': [('payment_method_code', 'not in', ['400', '240', '500'])]}"/>
            </field>

            <!-- TODO: Existe a possibilidade de alterar o Partner e ter um diferente
                  do informado na account.move.line ? Qual seria o caso de uso ? -->
            <field name="partner_id" position="attributes">
                <attribute name="attrs">{'readonly': [('payment_method_code', 'not in', ('400', '240', '500'))]}</attribute>
            </field>
            <field name="partner_id" position="after">
                <field name="partner_pix_id" context="{'default_partner_id': partner_id}" domain="[('partner_id', '=', partner_id)]" attrs="{'invisible': [('payment_type', '=', 'inbound')]}"/>
                <field name="pix_transfer_type" readonly="1"/>
            </field>
            <xpath expr="//field[@name='currency_id']" position="after">
                <!-- Os campos não podem ser alterados aqui porque isso precisa
                ser feito na respectiva account.move.line para ficar registrado para
                evitar inconsistencias de ter alterações não registradas -->
                <field name="percent_interest" readonly="1"/>
                <field name="amount_interest" readonly="1"/>
                <field name="rebate_value" readonly="1"/>
                <field name="discount_value" readonly="1"/>
            </xpath>
            <xpath expr="//group[@name='right']" position="after">
                <group name="cnab" string="Informações do CNAB">
                    <field name="own_number" readonly="1"/>
                    <field name="document_number" readonly="1"/>
                    <field name="payment_mode_domain" invisible="1"/>
                    <field name="barcode" attrs="{'required': [('payment_type', '=', 'outbound'),('payment_mode_domain', '=', 'boleto')]}"/>
                    <field name="company_title_identification" readonly="1"/>
                    <field name="movement_type" attrs="{'invisible': [('payment_method_code', '!=', '240')]}"/>
                    <field name="mov_instruction_code_id" readonly="1"/>
                    <field name="doc_finality_code" attrs="{'invisible': [('payment_type', '=', 'inbound')]}"/>
                    <field name="ted_finality_code" attrs="{'invisible': [('payment_type', '=', 'inbound')]}"/>
                    <field name="complementary_finality_code" attrs="{'invisible': [('payment_type', '=', 'inbound')]}"/>
                    <field name="favored_warning"/>
                    <field name="service_type"/>
                    <field name="payment_method_code" invisible="1"/>
                </group>
            </xpath>

        </data></field>
    </record>
2022-12-13 01:38:31,791 151890 INFO kimenz-prod odoo.modules.loading: loading 1 modules... 
2022-12-13 01:38:31,818 151890 INFO kimenz-prod odoo.modules.loading: 1 modules loaded in 0.03s, 0 queries (+0 extra) 
2022-12-13 01:38:32,161 151890 INFO kimenz-prod odoo.modules.loading: loading 262 modules... ```

**Comment by marcos-mendez** [comment]
@antoniospneto acho que este modulo foi tu que fez né?

Ao atualizar o l10n_br dá isso ai.

**Comment by antoniospneto** [comment]
@marcos-mendez tem certeza que você rodou o comando para atualizar os módulos corretamente ?
por que olhando o log parece que você atualizou o codigo fonte mas não rodou um **-u all**

Obs: Não existe módulo PIX, as funcionalidade para armazenar os dados PIX foram inseridos no módulo **l10n_br_base** e **l10n_br_account_payment**. confirme se vc deu um update nesses módulos.

**Comment by marcos-mendez** [comment]
@antoniospneto eu atualizei somente o l10n_br_fiscal que foi o modulo que eu atualizei os outros eu não mexi em nada

**Comment by antoniospneto** [comment]
@marcos-mendez mas você atualizou o código fonte, então é necessário que rode um update nos módulos tbm, pra vc não ter que ficar olhando módulo por módulo se houve alguma alteração nos modelos de dados, é mais pratico e também seguro rodar um -update all.

**Comment by antoniospneto** [comment]
@marcos-mendez acho que pode fechar a issue.
