### ISSUE TITLE
[14.0] Erro ao instalar LATAM Localization Base

### ISSUE THREAD

**Issue by igoroliveira-ax4b** [OCA/l10n-brazil#2285]
## Module

LATAM Localization Base

## Describe the bug

O Seguinte erro ocorre ao instalar o módulo LATAM Localization Base

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: <class 'odoo.tools.convert.ParseError'>: "while parsing /usr/lib/python3/dist-packages/odoo/addons/l10n_latam_base/views/res_partner_view.xml:4, near

<record id="view_partner_latam_form" model="ir.ui.view">
        <field name="name">view_partner_latam_form</field>
        <field name="inherit_id" ref="base.view_partner_form"/>
        <field name="model">res.partner</field>
        <field name="priority">100</field>
        <field type="xml" name="arch">
            <data><field name="vat" position="attributes">
                <attribute name="invisible">1</attribute>
            </field>
            <field name="vat" position="after">
                <label for="l10n_latam_identification_type_id" string="Identification Number"/>
                <div>
                    <field name="l10n_latam_identification_type_id" options="{'no_open': True, 'no_create': True}" placeholder="Type" attrs="{'readonly': [('parent_id','!=',False)]}" class="oe_inline" domain="country_id and ['|', ('country_id', '=', False), ('country_id', '=', country_id)] or []" required="True"/>
                    <span class="oe_read_only"> - </span>
                    <field name="vat" placeholder="Number" class="oe_inline" attrs="{'readonly': [('parent_id','!=',False)]}"/>
                </div>
            </field>
        </data></field>
    </record>" while evaluating

records.button_immediate_install()'
```

Alguém ja teve esse problema e solucionou?

**Comment by marcelsavegnago** [comment]
Se o seu objetivo é instalar a localização brasileira eu acho que está no caminho errado. Este módulo LATAM não faz parte do projeto da localização brasileira da OCA.

**Comment by marcelsavegnago** [comment]
Inclusive não utilizamos tbm o modulo l10n_br que está no core do Odoo.

**Comment by rvalyi** [comment]
> Inclusive não utilizamos tbm o modulo l10n_br que está no core do Odoo.

Só para completar: nós da Akretion fomos o autor original do modulo l10n_br uns 10 anos atras, mas já em volta dos anos 2014-2015 a Odoo SA deixava nossos PR para corrigir esse modulo em aberto por anos sem review e a gente desistiu de usar e criamos os modulos l10n_br_coa* no OCA/l10n_br. Não é diferente com muitas localizações: 

https://github.com/OCA/l10n-france/issues/379
https://github.com/OCA/OCB/pull/1138
https://github.com/odoo/odoo/pull/34163
