### ISSUE TITLE
[14.0] Erro na instalação do módulo l10n_br_account_payment_order

### ISSUE THREAD

**Issue by igoroliveira-ax4b** [OCA/l10n-brazil#2296]
## Module
l10n_br_account_payment_order
l10n_br_account_payment_brcobranca

## Describe the bug
O seguinte erro ocorre na instalação dos módulos citados

```
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 914, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1392, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1380, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-67>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 478, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 596, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 459, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 347, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 232, in load
    model = cls._build_model(self, cr)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 554, in _build_model
    raise TypeError("Model %r does not exist in registry." % name)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: Model 'bank.payment.line' does not exist in registry.
```

**Additional context**
Módulos `account_banking_*` instalados

**Comment by antoniospneto** [comment]
@IgorOliveiraAX4B

Recentemente houve uma alteração no módulo **account_payment_order** do repositório https://github.com/OCA/bank-payment.
Esse módulo é requisito para os módulos **l10n_br_account_payment_order** e **l10n_br_account_payment_brcobranca** aqui da localização.

Foi removido o modelo "bank.payment.line" quebrando compatibilidade dos módulos com os da localização.

Enquanto o problema não for resolvido aqui na localização, sugiro fazer um downgrade no repositório do bank-payment utilizar uma revisão antes dessa alteração, acho que se você apontar para esse commit já resolve: https://github.com/OCA/bank-payment/commit/55e9aff82ae282b3e26d85a05f3059e7bdbcd70c.

Ou, se tiver instalando os módulos pelo PIP apontar para uma versão assim:
odoo14-addon-account-payment-order<14.0.2.0.0

Essa é uma solução temporária enquanto aguardamos o trabalho voluntário de um colaborador com a correção dos módulos aqui na localização.

**Comment by antoniospneto** [comment]
Só pra manter a referencia, o assunto tá sendo discutido aqui também https://github.com/OCA/l10n-brazil/issues/2272

**Comment by igoroliveira-ax4b** [comment]
Resolvido!
Obrigado!

**Comment by mbcosta** [comment]
obrigado @IgorOliveiraAX4B por relatar o problema, procurei resolver isso no PR https://github.com/OCA/l10n-brazil/pull/2386 com isso volta a ser possível atualizar o modulo account_payment_order, se puder veja testar.
