### ISSUE TITLE
[14] Modulo de Compras - erro ao clicar na Opção Relatório

### ISSUE THREAD

**Issue by cs-tecnologia** [OCA/l10n-brazil#2298]
## Module
l10n_br_purchase

## Describe the bug
No menu de compras, quando clica na opção Relatario ocorre um erro e não abre o painel de relatorios.
![image](https://user-images.githubusercontent.com/114611246/212352553-c74dc95d-3796-4d39-bf4e-4c21999249c9.png)
Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 914, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1388, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1380, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 395, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 368, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/addons/purchase_stock/report/purchase_report.py", line 47, in read_group
    res = super(PurchaseReport, self).read_group(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/opt/odoo/odoo/addons/purchase/report/purchase_report.py", line 173, in read_group
    res = super(PurchaseReport, self).read_group(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/opt/odoo/odoo/odoo/models.py", line 2254, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/opt/odoo/odoo/odoo/models.py", line 2381, in _read_group_raw
    self._cr.execute(query, where_clause_params)
  File "<decorator-gen-3>", line 2, in execute
  File "/opt/odoo/odoo/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/sql_db.py", line 300, in execute
    res = self._obj.execute(query, params)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.errors.UndefinedTable: missing FROM-clause entry for table "cr"
LINE 55:             , SUM(l.price_unit / COALESCE(NULLIF(cr.rate, 0)...
                                                          ^

## To Reproduce
**Affected versions**:  14

1. Menu Opção Compras
2. no Menu Suspenso clicar em Relatórios

**Expected behavior**
Apresentar o Painel de Relatorios e graficos

**Additional context**
Fiz o teste no runboat da OCA e ocorre o mesmo problema.
Pela pesquisa que fiz, não esta sendo gerada a View "purchase_report" no banco.

**Comment by igoroliveira-ax4b** [comment]
@rvalyi o PR #2297 é referente à esse erro?

**Comment by rvalyi** [comment]
sim

**Comment by cs-tecnologia** [comment]
> @rvalyi o PR #2297 é referente à esse erro?

Sim, o mesmo problema. Já atualizei e fiz os teste tudo certo.
