### ISSUE TITLE
[14.0] l10n_br_fiscal nao instala sem demo data

### ISSUE THREAD

**Issue by PlaryWasTaken** [OCA/l10n-brazil#2306]
Erro ao instalar o modulo l10n_br_fiscal quando nao se utiliza os dados demo
Log completo do erro: Odoo Server Error

Traceback (most recent call last):
  File "/odooManager/odooManager-server/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/odooManager/odooManager-server/odoo/tools/convert.py", line 530, in _tag_record
    raise Exception("Cannot update missing record %r" % xid)
Exception: Cannot update missing record 'l10n_br_base.lucro_presumido_partner'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odooManager/odooManager-server/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/odooManager/odooManager-server/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/odooManager/odooManager-server/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odooManager/odooManager-server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odooManager/odooManager-server/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odooManager/odooManager-server/odoo/http.py", line 914, in __call__
    return self.method(*args, **kw)
  File "/odooManager/odooManager-server/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/odooManager/odooManager-server/addons/web/controllers/main.py", line 1392, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odooManager/odooManager-server/addons/web/controllers/main.py", line 1380, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odooManager/odooManager-server/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odooManager/odooManager-server/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "/odooManager/odooManager-server/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/odooManager/odooManager-server/odoo/addons/base/models/ir_module.py", line 478, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odooManager/odooManager-server/odoo/addons/base/models/ir_module.py", line 596, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odooManager/odooManager-server/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odooManager/odooManager-server/odoo/modules/loading.py", line 459, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/odooManager/odooManager-server/odoo/modules/loading.py", line 347, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/odooManager/odooManager-server/odoo/modules/loading.py", line 240, in load_module_graph
    getattr(py_module, post_init)(cr, registry)
  File "/usr/local/lib/python3.10/dist-packages/odoo14_addon_l10n_br_fiscal-14.0.10.5.1-py3.10.egg/odoo/addons/l10n_br_fiscal/hooks.py", line 81, in post_init_hook
    tools.convert_file(
  File "/odooManager/odooManager-server/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/odooManager/odooManager-server/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/odooManager/odooManager-server/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/odooManager/odooManager-server/odoo/tools/convert.py", line 681, in _tag_root
    raise ParseError('while parsing %s:%s, near\n%s' % (
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odooManager/odooManager-server/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odooManager/odooManager-server/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /usr/local/lib/python3.10/dist-packages/odoo14_addon_l10n_br_fiscal-14.0.10.5.1-py3.10.egg/odoo/addons/l10n_br_fiscal/demo/company_demo.xml:14, near
<record id="l10n_br_base.lucro_presumido_partner" model="res.partner">
        <field name="fiscal_profile_id" ref="l10n_br_fiscal.partner_fiscal_profile_cnt"/>
    </record>

**Comment by marcelsavegnago** [comment]
No arquivo de configuração vc pode mudar o parametro 
without-demo=True

ou adiciona o parametro --without-demo=True na linha de comando que está usando para executar o Odoo.
