### ISSUE TITLE
[14.0] Erro ao visualizar PDF de NF-e

### ISSUE THREAD

**Issue by igoroliveira-ax4b** [OCA/l10n-brazil#2331]
## Module
l10n_br_fiscal

## Describe the bug
Estou com o seguinte erro ao visualizar NF-e

```
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 914, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1392, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1380, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/extra-addons/l10n-brazil/l10n_br_account/models/account_invoice.py", line 541, in view_pdf
    return self.fiscal_document_id.view_pdf()
  File "/usr/lib/python3/dist-packages/odoo/extra-addons/l10n-brazil/l10n_br_nfe/models/document.py", line 846, in view_pdf
    self.make_pdf()
  File "/usr/lib/python3/dist-packages/odoo/extra-addons/l10n-brazil/l10n_br_nfse/models/document.py", line 75, in make_pdf
    return super().make_pdf()
  File "/usr/lib/python3/dist-packages/odoo/extra-addons/l10n-brazil/l10n_br_nfe/models/document.py", line 862, in make_pdf
    xml_string = base64.b64decode(arquivo.datas).decode()
  File "/usr/lib/python3.8/base64.py", line 80, in b64decode
    s = _bytes_from_decode_data(s)
  File "/usr/lib/python3.8/base64.py", line 45, in _bytes_from_decode_data
    raise TypeError("argument should be a bytes-like object or ASCII "
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: argument should be a bytes-like object or ASCII string, not 'bool'
```

É algum erro já conhecido?

## To Reproduce
Fiscal > Documentos > NF-e > Selecionar a NF-e validada > Visualizador PDF

**Comment by antoniospneto** [comment]
@IgorOliveiraAX4B 

Vá na configuração da empresa e configure o processador de documentos fiscais:

![image](https://user-images.githubusercontent.com/634278/216500906-cf9e4c1c-edee-4497-960e-0fda865202cd.png)

**Comment by igoroliveira-ax4b** [comment]
@antoniospneto 
Já havia me atentado à isso, está habilitado
Estou com as libs nessas versões

```
erpbrasil.edoc        2.2.1               
erpbrasil.edoc.pdf    1.1.0                       
```

**Comment by antoniospneto** [comment]
Depois de ativar o processador de documento faça a digitação da nota novamente, é que se não tiver o processador configurado o xml dá nota não é criado, ai dá erro na hora de tentar visualizar, inclusive no PDF que usa o xml como base.

**Comment by igoroliveira-ax4b** [comment]
O processador já estava ativo quando a NF-e foi criada, porém mesmo assim a visualização em PDF retorna o mesmo.

**Comment by antoniospneto** [comment]
dá uma conferida se o sistema gerou essas informações na aba "outros" do documento fiscal

![image](https://user-images.githubusercontent.com/634278/216670549-73b8418c-6544-49fc-a627-f78728a54e4d.png)

**Comment by igoroliveira-ax4b** [comment]
@antoniospneto se trata de uma NF de compra

**Comment by antoniospneto** [comment]
Por enquanto o módulo não gera visualizações das nota fiscais recebidas, apenas de notas de emissão própria.
essa funcionalidade tem que ser implementada, PR são bem vindas 👍🏻

**Comment by rvalyi** [comment]
se alguém implementar, sera se não valeria a pena apenae renderizar o XML anexado, se tiver, com o erpbrasil.edoc.pdf? Pois eu não sei se valeria a pena se dar o trabalho de tentar serializar uma NFe de entrada com XML, sendo que o que deve valer mesmo é o XML do fornecedor e que logo logo a gente consegue importa-lo.

**Comment by antoniospneto** [comment]
@rvalyi concordo com você , é o que eu penso tbm
