### ISSUE TITLE
Erro ao gerar arquivops de ordem de pagamento

### ISSUE THREAD

**Issue by alangalva** [OCA/l10n-brazil#2385]
## CNAB
Erro ao gerar arquivops de ordem de pagamento

## Describe the bug
Erro ao gerar arquivops de ordem de pagamento erro acontece quando clicamos em gerar arquivos (Generate payment file).

## To Reproduce
**Affected versions**:
Versão community 14

1.
2.
3.

**Expected behavior**

**Additional context**
Erro:
Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 914, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1392, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1380, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/mnt/extra-addons/l10n-brazil/l10n_br_account_payment_order/models/account_payment_order.py", line 111, in open2generated
    result = super().open2generated()
  File "/mnt/extra-addons/bank-payment/account_payment_order/models/account_payment_order.py", line 392, in open2generated
    payment_file_str, filename = self.generate_payment_file()
  File "/mnt/extra-addons/l10n-brazil/l10n_br_cnab_structure/models/account_payment_oder.py", line 73, in generate_payment_file
    str_file = self.cnab_structure_id.output(self).encode("utf-8")
  File "/mnt/extra-addons/l10n-brazil/l10n_br_cnab_structure/models/cnab_structure.py", line 330, in output
    cnab = self.output_dicts(pay_order)
  File "/mnt/extra-addons/l10n-brazil/l10n_br_cnab_structure/models/cnab_structure.py", line 295, in output_dicts
    cnab.header = self.get_header().output(pay_order, RecordType.HEADER)
  File "/mnt/extra-addons/l10n-brazil/l10n_br_cnab_structure/models/cnab_line.py", line 173, in output
    self.ensure_one()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5028, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Expected singleton: l10n_br_cnab.line()

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 914, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1392, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1380, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/mnt/extra-addons/l10n-brazil/l10n_br_account_payment_order/models/account_payment_order.py", line 111, in open2generated
    result = super().open2generated()
  File "/mnt/extra-addons/bank-payment/account_payment_order/models/account_payment_order.py", line 392, in open2generated
    payment_file_str, filename = self.generate_payment_file()
  File "/mnt/extra-addons/l10n-brazil/l10n_br_cnab_structure/models/account_payment_oder.py", line 73, in generate_payment_file
    str_file = self.cnab_structure_id.output(self).encode("utf-8")
  File "/mnt/extra-addons/l10n-brazil/l10n_br_cnab_structure/models/cnab_structure.py", line 330, in output
    cnab = self.output_dicts(pay_order)
  File "/mnt/extra-addons/l10n-brazil/l10n_br_cnab_structure/models/cnab_structure.py", line 295, in output_dicts
    cnab.header = self.get_header().output(pay_order, RecordType.HEADER)
  File "/mnt/extra-addons/l10n-brazil/l10n_br_cnab_structure/models/cnab_line.py", line 173, in output
    self.ensure_one()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5028, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Expected singleton: l10n_br_cnab.line()

**Comment by antoniospneto** [comment]
@alangalva 

Pelo que percebi o erro partiu do módulo **l10n_br_cnab_structure**.
Isso me parece que é a estrutura do arquivo de remessa que não foi configurada corretamente.
Confira no menu: Invoicing ->  Configuration -> CNAB Structures

Você pode me passar com mais detalhes a operação que você está tentando fazer?

É para uma conta de fornecedor que você está tentando gerar a ordem ?
Qual o Banco ?
Qual a forma de pagamento ?

**Comment by alangalva** [comment]
Olá, é uma ordem de para cliente, banco Itaú,
 Tipo de pagamento: Inbound, dinheiro

**Comment by alangalva** [comment]
![image](https://user-images.githubusercontent.com/127894352/225141736-74f4f147-a16e-4890-a038-46a513200618.png)

**Comment by antoniospneto** [comment]
A ordem de pagamento é para você fazer a automação bancária, troca de arquivo cnab (remessa e retorno) no seu caso que é cobrança, você tem que suar o meio de pagamento Boleto.

De uma olhada nos exemplos com os dados de demonstração, fica mais fácil para você estudar, utilize o módulo brcobranca para esse fim, não o l10n_br_cnab_structure, para você que tá iniciando sugiro que desinstale ele pra não gerar confusão , o l10n_br_cnab_structure atualmente tá implementando só para fazer a parte de pagamento de contas , não de recebimentos (cobrança)

**Comment by antoniospneto** [comment]
Acho que essa issue pode ser fechada, pelo que dá de entender foi apenas configuração/uso errado.

@OCA/local-brazil-maintainers
