### ISSUE TITLE
[12.0] Impossível acessar view da empresa/company

### ISSUE THREAD

**Issue by rpsjr** [OCA/l10n-brazil#2473]
## Module
?res.company?

## Describe the bug
É impossivel acessar as views das empresas/ editalas, o seguinte erro é retornado:

```
Error:
Uncaught TypeError: Cannot read properties of undefined (reading 'type')

http://oca-l10n-brazil-12-0-aaa4b68ec604.runboat.odoo-community.org/web/content/684-a8981fa/web.assets_backend.js:1534
Traceback:
TypeError: Cannot read properties of undefined (reading 'type')
    at Class._getFieldWidgetClass (http://oca-l10n-brazil-12-0-aaa4b68ec604.runboat.odoo-community.org/web/content/684-a8981fa/web.assets_backend.js:1534:62)
    at Class._processField (http://oca-l10n-brazil-12-0-aaa4b68ec604.runboat.odoo-community.org/web/content/684-a8981fa/web.assets_backend.js:1539:240)
    at Class._processNode (http://oca-l10n-brazil-12-0-aaa4b68ec604.runboat.odoo-community.org/web/content/684-a8981fa/web.assets_backend.js:1553:142)
    at http://oca-l10n-brazil-12-0-aaa4b68ec604.runboat.odoo-community.org/web/content/684-a8981fa/web.assets_backend.js:1539:136
    at Object.traverse (http://oca-l10n-brazil-12-0-aaa4b68ec604.runboat.odoo-community.org/web/content/683-02308d4/web.assets_common.js:3774:320)
    at http://oca-l10n-brazil-12-0-aaa4b68ec604.runboat.odoo-community.org/web/content/683-02308d4/web.assets_common.js:3774:368
    at _.each._.forEach (http://oca-l10n-brazil-12-0-aaa4b68ec604.runboat.odoo-community.org/web/content/683-02308d4/web.assets_common.js:12:558)
    at Object.traverse (http://oca-l10n-brazil-12-0-aaa4b68ec604.runboat.odoo-community.org/web/content/683-02308d4/web.assets_common.js:3774:331)
    at http://oca-l10n-brazil-12-0-aaa4b68ec604.runboat.odoo-community.org/web/content/683-02308d4/web.assets_common.js:3774:368
    at _.each._.forEach (http://oca-l10n-brazil-12-0-aaa4b68ec604.runboat.odoo-community.org/web/content/683-02308d4/web.assets_common.js:12:558)
```

## To Reproduce
**Affected versions**: 12.0 [http://oca-l10n-brazil-12-0-aaa4b68ec604.runboat.odoo-community.org]

1. Settings >> Users & Companies >> Companies
2. Tentar acessar qualquer das empresas

**Expected behavior**
A view da empresa está acessível.

**Comment by douglascstd** [comment]
@rpsjr para complementar o erro que você encontrou, acessei instâncias anteriores e esse erro não aparece por exemplo em: Apr 12

http://oca-l10n-brazil-12-0-0a6227e1fefe.runboat.odoo-community.org/web#id=2&action=48&model=res.company&view_type=form&menu_id=4

Entre essa instância, dei uma olhada, e parece que existem mudanças na PR #2471 
https://github.com/OCA/l10n-brazil/pull/2471
@renatonlima será que pode ser sido essa PR que impactou?

Não consegui identificar ainda

**Comment by rvalyi** [comment]
Realemente eu confirmo a regressão, obrigado por reportar. Acontece na 12 e não na 14. Debugando os assets parece que acontece com um campo chamado nfe40_choiceemit:
![2023-05-15_11-13](https://github.com/OCA/l10n-brazil/assets/16926/5d0a0ca7-8675-43a4-b0ef-7bd3c30b8629)

Porem, podem verificar com grep: nehnum campo se chama nfe40_choiceemit. Eu suspeito que isso tem a ver com a visão automatica dos campos de NFe que acontece na aba fiscal da empresa e que esta montado dinamicamente aqui: https://github.com/OCA/l10n-brazil/blob/12.0/spec_driven_model/models/spec_view.py#L22

Esse codigo ta bem beta e sem teste. Mas ai que ta, começei pelo refator pro xsdata e depois tem a consolidação desse metodo no meu radar.

Isso deve tb ter a ver com o fato que o generateDS cria attributos "choice" dentro dos bindings Python enquanto o xsdata não faz isso. No xsdata-odoo eu tb nao acrescento campos choice dentros dos mixins geridos, eu apenas detecto se um campo pertence de alguma tag choice.

Nisso eu adicionadei manualmente de volta algums campos choices que estavam faltando pro funcionamento da NFe:
https://github.com/OCA/l10n-brazil/pull/2471/commits/3beacf043caca98b6a5e82451c4bb334fa3c186d quando foi feito o merge dos mixins com xsdata semana passada. Talvez estaria faltando algum campo choice num dos mixins injectados no res.company para funcionar...

Um workaround poderia ser de renomar o metodo fields_view_get aqui https://github.com/OCA/l10n-brazil/blob/12.0/spec_driven_model/models/spec_view.py#LL22C9-L22C24 para ele nao ser chamado ou melhor retornar o super se self._name == "res.company"

Ainda é um misterio porque o problema não esta acontescendo na 14.0. Qualquer ajuda é bem vinda.

cc @renatonlima @marcelsavegnago @mileo @antoniospneto @felipemotter

**Comment by edsonblwolf** [comment]
Na 14.0 também.:
[https://imgur.com/eOQafAG.png](url)
[https://imgur.com/goM5oF8.png](url)
```

Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 370, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 358, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 919, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 544, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1370, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1362, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3012, in read
    raise ValueError("Invalid field %r on model %r" % (name, self._name))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 652, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field 'own_number_type' on model 'res.company'
```

**Comment by felipemotter** [comment]
Fala @edsonblwolf, isto não é o mesmo problema. Seu problema está linkado a PR [#2452](https://github.com/OCA/l10n-brazil/pull/2452) . De alguma forma o sistema de update do odoo não está lidando direito com a exclusão desse campo.


A solução não é bonita, mas resolve: exclua a view `l10n_br_account_payment_order.res.company.form` e depois rode um update all. Desta forma não vai ocorrer este erro e de qualquer forma ela já seria excluída....

**Comment by edsonblwolf** [comment]
Não achei @felipemotter :
[https://imgur.com/fiUQtBX.png](url)

**Comment by antoniospneto** [comment]
@edsonblwolf  não é nos arquivos .xml que você tem que olhar, é dentro da interface web do odoo mesmo, vai configurações -> visões e depois procura pelo nome que o felipe passou.

**Comment by edsonblwolf** [comment]
Tava ruim parece que pirou. kkk
[https://imgur.com/U9uGiX6.png](url)
Clico no voltar aparece esse erro.
[https://pastebin.com/AdgXXNVq](url)

**Comment by marcelsavegnago** [comment]
> Fala @edsonblwolf, isto não é o mesmo problema. Seu problema está linkado a PR [#2452](https://github.com/OCA/l10n-brazil/pull/2452) . De alguma forma o sistema de update do odoo não está lidando direito com a exclusão desse campo.
> 
> A solução não é bonita, mas resolve: exclua a view `l10n_br_account_payment_order.res.company.form` e depois rode um update all. Desta forma não vai ocorrer este erro e de qualquer forma ela já seria excluída....


Fizemos isso em uma recente atualização.
