### ISSUE TITLE
Erro ao instalar modulo l10n_br_fiscal_certificate Odoo 14 Python 3.6

### ISSUE THREAD

**Issue by KaiserBR** [OCA/l10n-brazil#2623]
Ao tentar instalar o modulo é reportado este erro.

Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo14/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo14/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo14/odoo/http.py", line 370, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo14/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo14/odoo/http.py", line 358, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo14/odoo/http.py", line 919, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo14/odoo/http.py", line 544, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo14/addons/web/controllers/main.py", line 1374, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo14/addons/web/controllers/main.py", line 1362, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo14/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo14/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo14/odoo/addons/base/models/res_config.py", line 642, in execute
    installation_status = self._install_modules(to_install)
  File "/opt/odoo/odoo14/odoo/addons/base/models/res_config.py", line 36, in _install_modules
    result = to_install_modules.button_immediate_install()
  File "<decorator-gen-72>", line 2, in button_immediate_install
  File "/opt/odoo/odoo14/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo14/odoo/addons/base/models/ir_module.py", line 478, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo14/odoo/addons/base/models/ir_module.py", line 596, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo14/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo14/odoo/modules/loading.py", line 461, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo14/odoo/modules/loading.py", line 349, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo14/odoo/modules/loading.py", line 240, in load_module_graph
    getattr(py_module, post_init)(cr, registry)
  File "/opt/odoo/l10n-brazil/l10n_br_fiscal_certificate/hooks.py", line 54, in post_init_hook
    prepare_fake_certificate_vals()
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo14/odoo/http.py", line 652, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo14/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'NoneType' object has no attribute 'certificate_nfe_id'

**Comment by marcelsavegnago** [comment]
As bibliotecas instaladas estão na versão que está destacado no requirements.txt ?

**Comment by KaiserBR** [comment]
Sim. conferi novamente agora. todas as dependências satisfeitas. 

Quando a instalação ocorre com os dados de demonstração, tudo ocorre normalmente.

O erro parece estar relacionado ao trecho de código a seguir. 

if not tools.config["without_demo"]:
        companies = [
            env.ref("base.main_company", raise_if_not_found=False),
            env.ref("l10n_br_base.empresa_lucro_presumido", raise_if_not_found=False),
            env.ref("l10n_br_base.empresa_simples_nacional", raise_if_not_found=False),
        ]
        try:
            for company in companies:
                l10n_br_fiscal_certificate_id = env["l10n_br_fiscal.certificate"]
                company.certificate_nfe_id = l10n_br_fiscal_certificate_id.create(
                    prepare_fake_certificate_vals()
                )
                company.certificate_ecnpj_id = l10n_br_fiscal_certificate_id.create(
                    prepare_fake_certificate_vals(cert_type=CERTIFICATE_TYPE_ECNPJ)
                )
        except NameError:  # (means from erpbrasil.assinatura import misc failed)
            _logger.error(
                _(
                    "Python Library erpbrasil.assinatura not installed!"
                    "You can install it later with: pip install erpbrasil.assinatura."
                    "Demo companies fake A1 certificates were not created."
                )

> As bibliotecas instaladas estão na versão que está destacada no requirements.txt ?

**Comment by laruzzo** [comment]
Tou com o mesmo problema aqui... se souberem de algo agradeço. Acho que deve estar faltando o script para criar as tabelas do postgree o código tenta incluir os dados fake do certificado digital e não encontra a tabela, acho que possa ser esse o problema. Obrigado

**Comment by laruzzo** [comment]
Vou testar com um banco de dados demo pra ver se instala aqui

**Comment by laruzzo** [comment]
Com o banco demo deu certo a instalação de todos os módulos

**Comment by moigamijunior** [comment]
Verifique em `odoo.conf` se `without_demo` está `True`. Deve ser `without_demo=True`.
