### ISSUE TITLE
OpenUpgrade v12->v13->v14: l10n_br_fiscal/migrations/14.0.11.0.0/post-migration.py non unique NCM

### ISSUE THREAD

**Issue by rvalyi** [OCA/l10n-brazil#2706]
Quando foi atualizado a tabela de NCM pela Engenere foi feito o script de migração l10n_br_fiscal/migrations/14.0.11.0.0/post-migration.py e depois um backport dele na v12. So que atualizando um banco da v12 até a v14 com OpenUpgrade, o Odoo tenta atualizar os ncm pela segunda vez na v14 então e isso da erro. Na minha instalação eu comentei o script da v14, mas o certo seria testar a presença de um ou alguns dos NCMs adicionais e não tentar atualizar os NCMs se ja tiver.

Bem segue aqui o erro, talvez o workaround serve caso alguem bate no mesmo erro:

```
2023-09-22 04:28:35,138 58 ERROR odoo14 odoo.sql_db: bad query: INSERT INTO "l10n_br_fiscal_ncm" ("id", "create_uid", "create_date", "write_uid", "write_date", "active", "code", "exception", "name", "tax_ii_id", "tax_ipi_id", "uoe_id") VALUES (nextval('l10n_br_fiscal_ncm_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), false, '6815.99.90', 'P', 'I.- PRODUTOS DE FARINHAS SILICIOSAS FÓSSEIS OU DE TERRAS SILICIOSAS SEMELHANTES E PRODUTOS REFRATÁRIOS', 40, NULL, 3) RETURNING id
ERROR: duplicate key value violates unique constraint "l10n_br_fiscal_ncm_fiscal_ncm_code_exception_uniq"
DETAIL:  Key (code, exception)=(6815.99.90, P) already exists.



2023-09-22 04:30:46,555 58 ERROR odoo14 odoo.sql_db: bad query: INSERT INTO "l10n_br_fiscal_ncm" ("id", "create_uid", "create_date", "write_uid", "write_date", "active", "code", "excep
tion", "name", "tax_ii_id", "tax_ipi_id", "uoe_id") VALUES (nextval('l10n_br_fiscal_ncm_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), false, '7020.00.90', 'P'
, 'I.- PÉROLAS NATURAIS OU CULTIVADAS, PEDRAS PRECIOSAS OU SEMIPRECIOSAS E SEMELHANTES', 42, NULL, 3) RETURNING id    
ERROR: duplicate key value violates unique constraint "l10n_br_fiscal_ncm_fiscal_ncm_code_exception_uniq"            
DETAIL:  Key (code, exception)=(7020.00.90, P) already exists.  
[...]
The values for the fields 'code, exception' already exist (they are probably 'Code, Exception' in the current model).
2023-09-22 04:30:51,084 58 WARNING odoo14 odoo.modules.loading: Transient module states were reset
2023-09-22 04:30:51,086 58 ERROR odoo14 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/odoo/src/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/src/odoo/modules/loading.py", line 455, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/odoo/src/odoo/modules/loading.py", line 347, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/odoo/src/odoo/modules/loading.py", line 227, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/odoo/external-src/openupgrade/openupgrade_framework/odoo_patch/odoo/modules/migration.py", line 18, in migrate_module
    MigrationManager.migrate_module._original_method(self, pkg, stage)
  File "/odoo/src/odoo/modules/migration.py", line 186, in migrate_module
    migrate(self.cr, installed_version)
  File "/env/lib/python3.8/site-packages/openupgradelib/openupgrade.py", line 2271, in wrapped_function
    func(
  File "/odoo/external-src/l10n-brazil/l10n_br_fiscal/migrations/14.0.11.0.0/post-migration.py", line 11, in migrate
    tools.convert_file(
  File "/odoo/src/odoo/tools/convert.py", line 729, in convert_file
```

cc @felipemotter @antoniospneto @renatonlima

**Comment by marcelsavegnago** [comment]
Eu tinha visto este erro inclusive na atualização da 14.0 mas não consegui avaliar ainda.
