### ISSUE TITLE
Erro ao adicionar múltiplas IEs no cadastro da empresa

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#2714]
1. Acesse uma empresa já criada;
2. Tente preencher o campo State Tax Numbers;
3. Será exibido o seguinte erro:

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 370, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 358, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 919, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 544, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 1370, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 1362, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/models.py", line 6260, in onchange
    record._update_cache(changed_values, validate=False)
  File "/opt/odoo/odoo/models.py", line 5202, in _update_cache
    cache.set(self, field, field.convert_to_cache(value, self, validate))
  File "/opt/odoo/odoo/fields.py", line 2668, in convert_to_cache
    id_ = comodel.new(value, origin=origin).id
  File "/opt/odoo/odoo/models.py", line 5556, in new
    record._update_cache(values, validate=False)
  File "/opt/odoo/odoo/models.py", line 5198, in _update_cache
    raise ValueError("Invalid field %r on model %r" % (e.args[0], self._name))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 652, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field 'logo' on model 'res.partner'
```

**Comment by mbcosta** [comment]
@mileo procurei resolver o problema no PR https://github.com/OCA/l10n-brazil/pull/2721

**Comment by mbcosta** [comment]
Acredito que o problema já foi resolvido no PR https://github.com/OCA/l10n-brazil/pull/2721 e o merge foi feito na última semana, por isso se não houver outro problema peço para quem puder dos PSC @renatonlima @rvalyi @marcelsavegnago @mileo encerrarem esse issue.
