### ISSUE TITLE
[13.0] OpenUpgrade

### ISSUE THREAD

**Issue by marcos-mendez** [OCA/l10n-brazil#2889]
Ao Executar o OpenUpgrade da versão 12.0 para a v13.0 

Me deparo com o error a seguir:

```
2024-01-21 20:54:45,756 6094 ERROR ismoke-prod odoo.sql_db: bad query:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_cofins_ncm_rel.ncm_id FROM fiscal_pis_cofins_ncm_rel, "l10n_br_fiscal_ncm"
                    WHERE 1=1 AND fiscal_pis_cofins_ncm_rel.piscofins_id IN (1) AND fiscal_pis_cofins_ncm_rel.ncm_id = l10n_br_fiscal_ncm.id
                     ORDER BY "l10n_br_fiscal_ncm"."code"    OFFSET 0
                
ERROR: column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^
 
2024-01-21 20:54:45,900 6094 ERROR ismoke-prod odoo.sql_db: bad query:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_cofins_ncm_rel.ncm_id FROM fiscal_pis_cofins_ncm_rel, "l10n_br_fiscal_ncm"
                    WHERE 1=1 AND fiscal_pis_cofins_ncm_rel.piscofins_id IN (1) AND fiscal_pis_cofins_ncm_rel.ncm_id = l10n_br_fiscal_ncm.id
                     ORDER BY "l10n_br_fiscal_ncm"."code"    OFFSET 0
                
ERROR: column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^
 
2024-01-21 20:54:45,901 6094 ERROR ismoke-prod odoo.sql_db: bad query:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_cofins_ncm_rel.ncm_id FROM fiscal_pis_cofins_ncm_rel, "l10n_br_fiscal_ncm"
                    WHERE 1=1 AND fiscal_pis_cofins_ncm_rel.piscofins_id IN (2) AND fiscal_pis_cofins_ncm_rel.ncm_id = l10n_br_fiscal_ncm.id
                     ORDER BY "l10n_br_fiscal_ncm"."code"    OFFSET 0
                
ERROR: column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^
 
2024-01-21 20:54:45,902 6094 ERROR ismoke-prod odoo.sql_db: bad query:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_cofins_ncm_rel.ncm_id FROM fiscal_pis_cofins_ncm_rel, "l10n_br_fiscal_ncm"
                    WHERE 1=1 AND fiscal_pis_cofins_ncm_rel.piscofins_id IN (3) AND fiscal_pis_cofins_ncm_rel.ncm_id = l10n_br_fiscal_ncm.id
                     ORDER BY "l10n_br_fiscal_ncm"."code"    OFFSET 0
                
ERROR: column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^
 
2024-01-21 20:54:45,903 6094 ERROR ismoke-prod odoo.sql_db: bad query:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_cofins_ncm_rel.ncm_id FROM fiscal_pis_cofins_ncm_rel, "l10n_br_fiscal_ncm"
                    WHERE 1=1 AND fiscal_pis_cofins_ncm_rel.piscofins_id IN (4) AND fiscal_pis_cofins_ncm_rel.ncm_id = l10n_br_fiscal_ncm.id
                     ORDER BY "l10n_br_fiscal_ncm"."code"    OFFSET 0
                
ERROR: column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^
 
2024-01-21 20:54:45,904 6094 ERROR ismoke-prod odoo.sql_db: bad query:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_cofins_ncm_rel.ncm_id FROM fiscal_pis_cofins_ncm_rel, "l10n_br_fiscal_ncm"
                    WHERE 1=1 AND fiscal_pis_cofins_ncm_rel.piscofins_id IN (5) AND fiscal_pis_cofins_ncm_rel.ncm_id = l10n_br_fiscal_ncm.id
                     ORDER BY "l10n_br_fiscal_ncm"."code"    OFFSET 0
                
ERROR: column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^
 
2024-01-21 20:54:45,904 6094 ERROR ismoke-prod odoo.sql_db: bad query:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_cofins_ncm_rel.ncm_id FROM fiscal_pis_cofins_ncm_rel, "l10n_br_fiscal_ncm"
                    WHERE 1=1 AND fiscal_pis_cofins_ncm_rel.piscofins_id IN (6) AND fiscal_pis_cofins_ncm_rel.ncm_id = l10n_br_fiscal_ncm.id
                     ORDER BY "l10n_br_fiscal_ncm"."code"    OFFSET 0
                
ERROR: column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^
 
2024-01-21 20:54:45,905 6094 ERROR ismoke-prod odoo.sql_db: bad query:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_cofins_ncm_rel.ncm_id FROM fiscal_pis_cofins_ncm_rel, "l10n_br_fiscal_ncm"
                    WHERE 1=1 AND fiscal_pis_cofins_ncm_rel.piscofins_id IN (7) AND fiscal_pis_cofins_ncm_rel.ncm_id = l10n_br_fiscal_ncm.id
                     ORDER BY "l10n_br_fiscal_ncm"."code"    OFFSET 0
                
ERROR: column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^
 
2024-01-21 20:54:45,906 6094 ERROR ismoke-prod odoo.sql_db: bad query:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_cofins_ncm_rel.ncm_id FROM fiscal_pis_cofins_ncm_rel, "l10n_br_fiscal_ncm"
                    WHERE 1=1 AND fiscal_pis_cofins_ncm_rel.piscofins_id IN (8) AND fiscal_pis_cofins_ncm_rel.ncm_id = l10n_br_fiscal_ncm.id
                     ORDER BY "l10n_br_fiscal_ncm"."code"    OFFSET 0
                
ERROR: column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^
 
2024-01-21 20:54:45,907 6094 ERROR ismoke-prod odoo.sql_db: bad query:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_cofins_ncm_rel.ncm_id FROM fiscal_pis_cofins_ncm_rel, "l10n_br_fiscal_ncm"
                    WHERE 1=1 AND fiscal_pis_cofins_ncm_rel.piscofins_id IN (9) AND fiscal_pis_cofins_ncm_rel.ncm_id = l10n_br_fiscal_ncm.id
                     ORDER BY "l10n_br_fiscal_ncm"."code"    OFFSET 0
                
ERROR: column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^
 
2024-01-21 20:54:45,907 6094 ERROR ismoke-prod odoo.sql_db: bad query:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_cofins_ncm_rel.ncm_id FROM fiscal_pis_cofins_ncm_rel, "l10n_br_fiscal_ncm"
                    WHERE 1=1 AND fiscal_pis_cofins_ncm_rel.piscofins_id IN (10) AND fiscal_pis_cofins_ncm_rel.ncm_id = l10n_br_fiscal_ncm.id
                     ORDER BY "l10n_br_fiscal_ncm"."code"    OFFSET 0
                
ERROR: column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^
 
2024-01-21 20:54:46,003 6094 ERROR ismoke-prod odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/home/openupgrade/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/openupgrade/odoo/modules/loading.py", line 489, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/home/openupgrade/odoo/modules/loading.py", line 368, in load_marked_modules
    upg_registry=upg_registry,
  File "/home/openupgrade/odoo/modules/loading.py", line 248, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/home/openupgrade/odoo/modules/loading.py", line 72, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/openupgrade/odoo/tools/convert.py", line 737, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/home/openupgrade/odoo/tools/convert.py", line 784, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading l10n_br_fiscal failed: file l10n_br_fiscal/data/l10n_br_fiscal.tax.pis.cofins.csv could not be processed:
 column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^

column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^

column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^

column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^

column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^

column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^

column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^

column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^

column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^

column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^

Encontrados mais de 10 erros e mais de um erro por 10 registros, interrompido para evitar a exibição de muitos erros.
2024-01-21 20:54:46,004 6094 CRITICAL ismoke-prod odoo.service.server: Failed to initialize database `ismoke-prod`. 
Traceback (most recent call last):
  File "/home/openupgrade/odoo/service/server.py", line 1194, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/openupgrade/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/openupgrade/odoo/modules/loading.py", line 489, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/home/openupgrade/odoo/modules/loading.py", line 368, in load_marked_modules
    upg_registry=upg_registry,
  File "/home/openupgrade/odoo/modules/loading.py", line 248, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/home/openupgrade/odoo/modules/loading.py", line 72, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/openupgrade/odoo/tools/convert.py", line 737, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/home/openupgrade/odoo/tools/convert.py", line 784, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading l10n_br_fiscal failed: file l10n_br_fiscal/data/l10n_br_fiscal.tax.pis.cofins.csv could not be processed:
 column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^

column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^

column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^

column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^

column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^

column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^

column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^

column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^

column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^

column fiscal_pis_cofins_ncm_rel.piscofins_id does not exist
LINE 1:  SELECT fiscal_pis_cofins_ncm_rel.piscofins_id, fiscal_pis_c...
                ^

Encontrados mais de 10 erros e mais de um erro por 10 registros, interrompido para evitar a exibição de muitos erros.



```

Infelizmente não consigo reconhecer qual é o motivo da falha já que não está especificado no OpenUpgrade qual deveria ser a migração da l10-brazil nestes casos. Enfim no aguardo de alguma alma que possa ajudar. Obrigado

**Comment by felipemotter** [comment]
Não houve nenhuma ajuda do GPT?

**Comment by marcos-mendez** [comment]
> Não houve nenhuma ajuda do GPT?

Ele informa que há uma ausência da coluna pis_confins no banco de dados o que faz total sentido, porém ao informar que estou executando o comando update-all do odoo ele informa que provavlemente é um erro no código do Odoo e que contate o suporte rsrs

Como eu não estou habituado a lidar com o fiscal dentro do banco de dados não saberia dizer que o correto é criar essa tabela na mão e muito menos qual seriam as colunas e tipos de dados que deveriam ser configurados. 

A minha idéia é colocar a coluna na mão e fazer o upgrade de novo, mas por ser de antemão um problema de update do código da l10n-brazil coloquei aqui pois pode ser um problema de outra pessoa e também pelo fato de que talvez exista alguma PR que resolveu isto em algum momento porem foi removida da ultima versão estável da v12.

**Comment by marcelsavegnago** [comment]
Precisa identificar o que mudou em relação a esta coluna comparando o codigo da 12 para 13. Ai talvez precise de um script de migração no modulo .. vc colocaria uma pasta chamada migration/13.0.1.0.0 por exemplo

**Comment by rvalyi** [comment]
Pessoal, a forma como a gente migra um banco com l10n-brazil da 12.0 para 14.0 é não botando a branch 13.0 do l10n-brazil no addons_path.

O motivo é que a migração dos modulos l10n_br_fiscal e l10n_br_account para a v13 foi muito superficial (apenas como etapa para a v14 já que a migração para a v14 foi a segunda mais dificil depois da migração da v9) e tambem não houve contribuições para manter a branch 13.0 com front-ports da 12.0 ou back-ports da 14.0.

Nisso o modulo l10n_br_fiscal evoluiu muito mais na branch 12.0 do que na 13.0. Isso cria problemas ao tentar jogar a branch 13.0 do l10n-brazil no addons_path para migrar... Eh melhor nem botar e apenas rodas as atualizações na 12.0 e depois na 14.0.

Do restante é sempre bom respeitar quem faz os projetos open source que vc usa, ajuda a ser respeitado de volta e quem sabe receber ajuda...

Se houver mais duvida com isso podem re-abrir.
