### ISSUE TITLE
Erro ao gerar regra de posições fiscais

### ISSUE THREAD

**Issue by falexandresilva** [OCA/l10n-brazil#293]
Versão atualizada em 03/04/16.

Para reproduzir: Contabilidade, configuração, contas, modelos, gerar regras de posição fiscal.

Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 539, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 576, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/openerp/http.py", line 309, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/openerp/http.py", line 805, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/openerp/http.py", line 405, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 399, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/localizacao/l10n-brazil/l10n_br_account/models/account_fiscal_position_rule.py", line 149, in action_create
    from_country = fpr_template.from_country.id or False
  File "/opt/odoo/openerp/fields.py", line 834, in __get__
    self.determine_value(record)
  File "/opt/odoo/openerp/fields.py", line 927, in determine_value
    record._prefetch_field(self)
  File "/opt/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 3242, in _prefetch_field
    result = records.read(list(fnames), load='_classic_write')
  File "/opt/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 3179, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 3311, in _read_from_database
    cr.execute(query_str, [tuple(sub_ids)] + where_params)
  File "/opt/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/opt/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
  File "/usr/lib/python2.7/dist-packages/psycopg2/extensions.py", line 129, in getquoted
    pobjs = [adapt(o) for o in self._seq]
ProgrammingError: can't adapt type 'account.fiscal.position.rule.template'

**Comment by rvalyi** [comment]
@falexandresilva vc poderia especificar as branches que usa e se isso ainda acontece nas branch 8.0 da OCA?

**Comment by falexandresilva** [comment]
A branch 8.0 da OCA, o erro não acontece mais, porém não é gerado nenhuma regra de posição fiscal.

**Comment by rvalyi** [comment]
@falexandresilva ok. E porque vc precisa cria templates de posicoes fiscais para ele gerar. Entao nao tem mais bug aqui, vou fechar para nao poluir o tracker.
