### ISSUE TITLE
Stacked models saem do registry constantemente.

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#3155]
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 652, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.errors.UndefinedColumn: column l10n_br_fiscal_document.nfe40_ide does not exist
LINE 1: ..._fiscal_document"."date_in_out" as "date_in_out", "l10n_br_f...
```

De vez em quando em produção os campos de um modelo stacked saem do registry, provavelmente quando
um worker é reiniciado, ainda estamos investigando.

**Comment by rvalyi** [comment]
vc chegou a testar se isso resolve seu caso? https://github.com/OCA/l10n-brazil/pull/2725

**Comment by rvalyi** [comment]
Resolvido por https://github.com/OCA/l10n-brazil/pull/3335
