### ISSUE TITLE
[14.0] Error ao transmitir a nf-e

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#3425]
```
Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 370, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 358, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 919, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 544, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1374, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1362, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 406, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 391, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/auto/addons/l10n_br_account/models/account_move.py", line 572, in action_document_send
    invoice.fiscal_document_ids.action_document_send()
  File "/opt/odoo/auto/addons/l10n_br_fiscal_edi/models/document.py", line 182, in action_document_send
    return self._action_document_send()
  File "/opt/odoo/auto/addons/l10n_br_fiscal_edi/models/document_workflow.py", line 319, in _action_document_send
    to_send._document_send()
  File "/opt/odoo/auto/addons/l10n_br_fiscal_edi/models/document.py", line 238, in _document_send
    electronic._eletronic_document_send()
  File "/opt/odoo/auto/addons/l10n_br_nfe/models/document.py", line 1238, in _eletronic_document_send
    record._nfe_send_for_authorization()
  File "/opt/odoo/auto/addons/l10n_br_nfe/models/document.py", line 1247, in _nfe_send_for_authorization
    for service_response in nfe_manager.processar_documento(serialized_nfe):
  File "/usr/local/lib/python3.8/site-packages/erpbrasil/edoc/edoc.py", line 135, in processar_documento
    proc_envio = self.envia_documento(edoc)
  File "/usr/local/lib/python3.8/site-packages/erpbrasil/edoc/nfe.py", line 811, in envia_documento
    return self._post(
  File "/usr/local/lib/python3.8/site-packages/nfelib/nfe/ws/edoc_legacy.py", line 77, in _post
    with self._transmissao.cliente(url):
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/erpbrasil/transmissao/transmissao.py", line 77, in cliente
    self._cliente = Client(
  File "/usr/local/lib/python3.8/site-packages/zeep/client.py", line 76, in __init__
    self.wsdl = Document(wsdl, self.transport, settings=self.settings)
  File "/usr/local/lib/python3.8/site-packages/zeep/wsdl/wsdl.py", line 92, in __init__
    self.load(location)
  File "/usr/local/lib/python3.8/site-packages/zeep/wsdl/wsdl.py", line 95, in load
    document = self._get_xml_document(location)
  File "/usr/local/lib/python3.8/site-packages/zeep/wsdl/wsdl.py", line 155, in _get_xml_document
    return load_external(
  File "/usr/local/lib/python3.8/site-packages/zeep/loader.py", line 90, in load_external
    return parse_xml(content, transport, base_url, settings=settings)
  File "/usr/local/lib/python3.8/site-packages/zeep/loader.py", line 66, in parse_xml
    raise XMLSyntaxError(
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 652, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
zeep.exceptions.XMLSyntaxError: Invalid XML content received (Extra content at the end of the document, line 27, column 1)
```

**Comment by antoniospneto** [comment]
@mileo to fechando esse ok, é o que foi resolvido em https://github.com/erpbrasil/erpbrasil.edoc/pull/84 certo?
