### ISSUE TITLE
[16.0][BUG] - l10n_br_account - Erro na impressão de PDF

### ISSUE THREAD

**Issue by renanteixeira** [OCA/l10n-brazil#3432]
## Module
l10n_br_account

## Describe the bug
Após instalar o módulo l10n_br_account, não é mais possível imprimir relatórios PDF no sistema.
Traceback (most recent call last):
  File "/opt/odoo/addons/web/controllers/report.py", line 113, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter, context=context)
  File "/opt/odoo/odoo/http.py", line 734, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo-venv/lib/python3.10/site-packages/odoo/addons/report_xlsx/controllers/main.py", line 49, in report_routes
    return super().report_routes(reportname, docids, converter, **data)
  File "/opt/odoo/odoo/http.py", line 734, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/addons/web/controllers/report.py", line 42, in report_routes
    pdf = report.with_context(context)._render_qweb_pdf(reportname, docids, data=data)[0]
TypeError: IrActionsReport._render_qweb_pdf() got multiple values for argument 'data'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPC_ERROR
        at makeErrorFromResponse (http://oca-l10n-brazil-16-0-bf60b0d93b26.runboat.odoo-community.org/web/assets/679-001b8a1/web.assets_backend.min.js:997:163)
        at decoder.onload (http://oca-l10n-brazil-16-0-bf60b0d93b26.runboat.odoo-community.org/web/assets/679-001b8a1/web.assets_backend.min.js:984:7)

## To Reproduce
**Affected versions**: 16.0

1. Testado localmente e também no RunBoat
2. Abra qualquer registro que tenha um relatório PDF, por exemplo uma fatura
3. Clique em Imprimir -> Invoices
![image](https://github.com/user-attachments/assets/1d7fd05b-3dea-46c3-b844-e5134bf8862b)
![image](https://github.com/user-attachments/assets/063b6d80-e7e5-4f03-897e-cafa30f0f7a3)

**Expected behavior**
Download do arquivo PDF relacionado ao registro

**Additional context**
Ao remover o módulo l10n_br_account o arquivo é baixado normalmente.

**Comment by antoniospneto** [comment]
Eu imagino que isso deve estar relacionado ao override que é feito para a DANFE.
Vamos dar uma analisada nisso ok

**Comment by antoniospneto** [comment]
Resolvido no #3439
