### ISSUE TITLE
Erro ao confirmar NFe

### ISSUE THREAD

**Issue by bergpinheiro** [OCA/l10n-brazil#512]
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 955, in exec_workflow
    return request.session.exec_workflow(model, id, signal)
  File "/opt/odoo/openerp/http.py", line 1118, in exec_workflow
    r = self.proxy('object').exec_workflow(self.db, self.uid, self.password, model, signal, id)
  File "/opt/odoo/openerp/http.py", line 886, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/opt/odoo/openerp/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/openerp/service/model.py", line 37, in dispatch
    res = fn(db, uid, *params)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 188, in exec_workflow
    return exec_workflow_cr(cr, uid, obj, signal, *args)
  File "/opt/odoo/openerp/service/model.py", line 182, in exec_workflow_cr
    return execute_cr(cr, uid, obj, 'signal_workflow', [res_id], signal)[res_id]
  File "/opt/odoo/openerp/service/model.py", line 164, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 3575, in signal_workflow
    result[res_id] = workflow.trg_validate(uid, self._name, res_id, signal, cr)
  File "/opt/odoo/openerp/workflow/__init__.py", line 85, in trg_validate
    return WorkflowService.new(cr, uid, res_type, res_id).validate(signal)
  File "/opt/odoo/openerp/workflow/service.py", line 91, in validate
    res2 = wi.validate(signal)
  File "/opt/odoo/openerp/workflow/instance.py", line 80, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 116, in process
    if not self._execute(activity, stack):
  File "/opt/odoo/openerp/workflow/workitem.py", line 162, in _execute
    returned_action = self.wkf_expr_execute(activity)
  File "/opt/odoo/openerp/workflow/workitem.py", line 313, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/opt/odoo/openerp/workflow/workitem.py", line 291, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/opt/odoo/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/localizacao/odoo-brazil-eletronic-documents/nfe/models/account_invoice.py", line 80, in nfe_export
    self.env.context)
  File "/opt/odoo/localizacao/l10n-brazil/l10n_br_account_product/sped/nfe/document.py", line 702, in get_xml
    for nfe in self._serializer(cr, uid, ids, nfe_environment, context):
  File "/opt/odoo/localizacao/l10n-brazil/l10n_br_account_product/sped/nfe/document.py", line 48, in _serializer
    self._emmiter(invoice, company)
  File "/opt/odoo/localizacao/l10n-brazil/l10n_br_account_product/sped/nfe/document.py", line 229, in _emmiter
    invoice.company_id.partner_id.legal_name[:60])
  File "/usr/local/lib/python2.7/dist-packages/PySPED-0.1.2-py2.7.egg/pysped/xml_sped/base.py", line 270, in set_valor
    raise ErroCaracterInvalido(self.codigo, self.nome, self.propriedade, novo_valor, c)
ValueError: "" while evaluating
u'nfe_export()'

Alguem pode me ajudar?

**Comment by Daniel-Furcht** [comment]
Não vejo este erro acontecendo aqui.
Usas caracteres especiais (ç, caracteres acentuados, etc) no produto ou observações da NFe em questão?

**Comment by sadamo** [comment]
File "/opt/odoo/localizacao/l10n-brazil/l10n_br_account_product/sped/nfe/document.py", line 229, in _emmiter
invoice.company_id.partner_id.legal_name[:60])

Aqui indica que o erro está na razão social da empresa que está emitindo a nota. Tente apagar e reescrever a razão social da sua empresa.

**Comment by bergpinheiro** [comment]
Apaguei e reescrevi a razão social e deu esse erro:

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 955, in exec_workflow
    return request.session.exec_workflow(model, id, signal)
  File "/opt/odoo/openerp/http.py", line 1118, in exec_workflow
    r = self.proxy('object').exec_workflow(self.db, self.uid, self.password, model, signal, id)
  File "/opt/odoo/openerp/http.py", line 886, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/opt/odoo/openerp/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/openerp/service/model.py", line 37, in dispatch
    res = fn(db, uid, *params)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 188, in exec_workflow
    return exec_workflow_cr(cr, uid, obj, signal, *args)
  File "/opt/odoo/openerp/service/model.py", line 182, in exec_workflow_cr
    return execute_cr(cr, uid, obj, 'signal_workflow', [res_id], signal)[res_id]
  File "/opt/odoo/openerp/service/model.py", line 164, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 3575, in signal_workflow
    result[res_id] = workflow.trg_validate(uid, self._name, res_id, signal, cr)
  File "/opt/odoo/openerp/workflow/__init__.py", line 85, in trg_validate
    return WorkflowService.new(cr, uid, res_type, res_id).validate(signal)
  File "/opt/odoo/openerp/workflow/service.py", line 91, in validate
    res2 = wi.validate(signal)
  File "/opt/odoo/openerp/workflow/instance.py", line 80, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 116, in process
    if not self._execute(activity, stack):
  File "/opt/odoo/openerp/workflow/workitem.py", line 162, in _execute
    returned_action = self.wkf_expr_execute(activity)
  File "/opt/odoo/openerp/workflow/workitem.py", line 313, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/opt/odoo/openerp/workflow/workitem.py", line 291, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/opt/odoo/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/localizacao/odoo-brazil-eletronic-documents/nfe/models/account_invoice.py", line 80, in nfe_export
    self.env.context)
  File "/opt/odoo/localizacao/l10n-brazil/l10n_br_account_product/sped/nfe/document.py", line 702, in get_xml
    for nfe in self._serializer(cr, uid, ids, nfe_environment, context):
  File "/opt/odoo/localizacao/l10n-brazil/l10n_br_account_product/sped/nfe/document.py", line 55, in _serializer
    self._details(invoice, inv_line, i)
  File "/opt/odoo/localizacao/l10n-brazil/l10n_br_account_product/sped/nfe/document.py", line 383, in _details
    self.det.imposto.ICMS.CST.valor = invoice_line.icms_cst_id.code
  File "/usr/local/lib/python2.7/dist-packages/PySPED-0.1.2-py2.7.egg/pysped/nfe/leiaute/nfe_200.py", line 418, in set_valor
    super(TagCSTICMS, self).set_valor(novo_valor)
  File "/usr/local/lib/python2.7/dist-packages/PySPED-0.1.2-py2.7.egg/pysped/nfe/leiaute/nfe_110.py", line 915, in set_valor
    super(TagCSTICMS, self).set_valor(novo_valor)
  File "/usr/local/lib/python2.7/dist-packages/PySPED-0.1.2-py2.7.egg/pysped/xml_sped/base.py", line 268, in set_valor
    for c in novo_valor:
ValueError: "'bool' object is not iterable" while evaluating
u'nfe_export()'

**Comment by bergpinheiro** [comment]
Ao tentar imprimir a DANFE aparece o erro:
'bool' object has no attribute '__getitem__'

<type 'exceptions.TypeError'>,'bool' object has no attribute '__getitem__',<traceback object at 0x7f47843ab758>


Não sou programador se alguém puder me ajudar?

**Comment by sadamo** [comment]
Com relação ao erro 'nfe_export', é algum problema na CST do ICMS de alguma linha.

**Comment by sadamo** [comment]
A DANFE só pode ser impressa quando a fatura já foi confirmada.

**Comment by bergpinheiro** [comment]
Não sei onde encontro esse CST do Icms

**Comment by bergpinheiro** [comment]
sadamo voce faz uma verificação? Quanto cobra?

**Comment by bergpinheiro** [comment]
Consegui era esse tal de CST mesmo
