### ISSUE TITLE
[12] Erro ao validar NFe

### ISSUE THREAD

**Issue by jonatasartur** [OCA/l10n-brazil#721]
Estou com o Odoo 12, e aparece o seguinte erro ao tentar validar a NFe.

Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/home/teste/Odoo/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/teste/Odoo/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/teste/Odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/teste/Odoo/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/home/teste/Odoo/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/teste/Odoo/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/teste/Odoo/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/teste/Odoo/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/teste/Odoo/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/teste/Odoo/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/teste/Odoo/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/teste/Odoo/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/teste/Odoo/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/teste/Odoo/odoo/addons/sale/models/account_invoice.py", line 59, in action_invoice_open
    res = super(AccountInvoice, self).action_invoice_open()
  File "/home/teste/Odoo/odoo/addons/account/models/account_invoice.py", line 964, in action_invoice_open
    return to_open_invoices.invoice_validate()
  File "/home/teste/Odoo/odoo-brasil/br_account_einvoice/models/account_invoice.py", line 258, in invoice_validate
    eletronic.action_post_validate()
  File "/home/teste/Odoo/odoo-brasil/br_nfe/models/invoice_eletronic.py", line 896, in action_post_validate
    nfe_values = self._prepare_eletronic_invoice_values()
  File "/home/teste/Odoo/odoo-brasil/br_nfe/models/invoice_eletronic.py", line 441, in _prepare_eletronic_invoice_values
    tz = timezone(self.env.user.tz)
  File "/home/teste/.local/lib/python3.5/site-packages/pytz/__init__.py", line 163, in timezone
    if zone.upper() == 'UTC':
AttributeError: 'bool' object has no attribute 'upper'

Alguém ai tem ideia do que possa ser?

**Comment by rvalyi** [comment]
Ola @jonatasartur, ao que tudo indica vc esta usando algum fork selvagem da OCA mas não o código da OCA (o modulo br_account_einvoice nao eh da OCA). Portanto vc deveria procurar suporte com que fez o código que vc esta usando. Se vc quer emitir NFe com o codigo da OCA, vc tem que usar as branches 8 ou 10 (com um PR do modulo nfe, hoje). Na v12 vai ter os PR para emitir NFe em condicoes simples daqui umas 3 semanas (antes de forma experimental com PR). E sera completamanente integrado aos fluxos de venda, estoque, ou compra ate o fim do ano (necessita de migrar todos módulos da v10). A OCA tem como prioridade a qualidade e sustentabilidade das migrações de uma versão para outra. Algumas outras empresas tem outras prioridades.

Do restante ta parecendo que o timezone do seu servidor nao deve ser corretamente configurado, de forma que a lib pytz nao esta funcionando. Talvez alguma variável de ambiente para vc configurar.
