### ISSUE TITLE
[12.0] l10n_br_base Erro ao instalar para testes

### ISSUE THREAD

**Issue by augustodinizl** [OCA/l10n-brazil#764]
@renatonlima boa noite
Acredito que o ir.model.access esteja com algum erro, fui testar os campos solicitados na issue #762 e surgiu o seguinte erro:

`Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20191018-py3.7.egg/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20191018-py3.7.egg/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20191018-py3.7.egg/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20191018-py3.7.egg/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20191018-py3.7.egg/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20191018-py3.7.egg/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20191018-py3.7.egg/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20191018-py3.7.egg/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20191018-py3.7.egg/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20191018-py3.7.egg/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20191018-py3.7.egg/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20191018-py3.7.egg/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20191018-py3.7.egg/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20191018-py3.7.egg/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20191018-py3.7.egg/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20191018-py3.7.egg/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20191018-py3.7.egg/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20191018-py3.7.egg/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20191018-py3.7.egg/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20191018-py3.7.egg/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20191018-py3.7.egg/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20191018-py3.7.egg/odoo/tools/convert.py", line 798, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20191018-py3.7.egg/odoo/tools/convert.py", line 845, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Carregamento do Módulo l10n_br_base falhou: arquivo l10n_br_base/security/ir.model.access.csv não pode ser processado:
 Nenhum registro encontrado para id externo 'model_state_tax_numbers' no campo 'Object'
Nenhum registro encontrado para id externo 'model_state_tax_numbers' no campo 'Object'
Faltando valor necessário para o campo 'Object' (model_id)
Faltando valor necessário para o campo 'Object' (model_id)`

**Comment by renatonlima** [comment]
Eu vi que no seu PR, tem um erro na definição do campo crc_uf, isso deve esta causando o erro na instalação do módulo.
