### ISSUE TITLE
[12.0] Configuração Empresa

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#810]
**1o Passo - Preparação da Base de Dados e Instalação dos Módulos Básicos.**
 ./core/odoo-bin -c odoo.conf -d new-db -i l10n_br_fiscal,l10n_br_account --without-demo=all —-stop-after-init

Instalação foi bem sucedido

**2o Passo - Configuração da Empresa.**
Settings / Set Up (Company)
![image](https://user-images.githubusercontent.com/3595132/78852833-c9ed3000-79f3-11ea-9fbd-77c726e53bda.png)

Preenchi apenas os campos obrigatórios e ao tentar salvar o registro eu recebi a seguinte mensagem de erro:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/oca/l10n-brazil/l10n_br_base/models/res_company.py", line 193, in write
    result = super(Company, self).write(values)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/addons/base/models/res_company.py", line 239, in write
    return super(Company, self).write(values)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/models.py", line 3344, in write
    self._write(store_vals)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/models.py", line 3474, in _write
    field.write(other, vals[field.name])
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/fields.py", line 2565, in write
    flush()
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/fields.py", line 2526, in flush
    comodel.create(vals_list)
  File "<decorator-gen-208>", line 2, in create
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/api.py", line 443, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/api.py", line 443, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/oca/l10n-brazil/l10n_br_fiscal/models/tax_definition.py", line 251, in create
    create_super = super(TaxDefinition, self).create(values)
  File "<decorator-gen-116>", line 2, in create
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/api.py", line 461, in _model_create_multi
    return create(self, [arg])
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/addons/mail/models/mail_thread.py", line 272, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/models.py", line 3583, in create
    records = self._create(data_list)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/models.py", line 3683, in _create
    cr.execute(query, params)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: null value in column "tax_group_id" violates not-null constraint
DETAIL:  Failing row contains (327, null, out, null, f, null, null, null, f, f, 1, null, null, null, null, null, null, null, null, draft, null, null, null, null, null, 2, 2020-04-09 02:53:06.402329, 2, 2020-04-09 02:53:06.402329).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/addons/account/models/company.py", line 285, in write
    return super(ResCompany, self).write(values)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/addons/product/models/res_company.py", line 70, in write
    return super(ResCompany, self).write(values)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/oca/l10n-brazil/l10n_br_base/models/res_company.py", line 198, in write
    raise Exception
Exception

**Comment by gabrielcardoso21** [comment]
Fiz um PR corrigindo esse erro https://github.com/OCA/l10n-brazil/pull/817
