### ISSUE TITLE
[12.0] Seleção Tax Framework (Company)

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#811]
Instância Odoo sem dados de demonstração

Na tela de configuração da empresa **Settings / Set Up** 

Ao alterar o campo Tax Framework para Simples Nacional ou Simples Nacional - excesso de sublimite da receita bruta, recebi a seguinte mensagem de erro:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/models.py", line 5533, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/models.py", line 5377, in _onchange_eval
    method_res = method(self)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/oca/l10n-brazil/l10n_br_fiscal/models/res_company.py", line 353, in _onchange_piscofins_id
    self._set_tax_definition(self.piscofins_id.tax_cofins_id)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/oca/l10n-brazil/l10n_br_fiscal/models/res_company.py", line 278, in _set_tax_definition
    tax_def.update(tax_def_values)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/models.py", line 4944, in update
    record[name] = value
  File "/Users/marcelsavegnago/Projetos/odoo/odoo12/core/odoo/models.py", line 5152, in __setitem__
    return self._fields[key].__set__(self, value)
KeyError: 'tax_withholding'

**Comment by renatonlima** [comment]
Olá @marcelsavegnago,

Isso ocorre porque o campo tax_withholding não existe mais no objeto l10n_br_fiscal.tax.definition, pois esse flag já esta no l10n_br_fiscal.tax.group. eu fiz um fix #812 você usar o Runbot da OCA para testar ou fazer pull da branch do PR para testar localmente.
